export const modelParts = [
  "Primary Fence",
  "Secondary Fence",
  "Exterior Rail",
  "Interior Options",
];
export const initialColors = {
  "Primary Fence": "#424142",
  "Secondary Fence": "#424142",
  "Exterior Rail": "#D5E2E6",
  "Interior Options": "#B8AB9E",
};

export const colorOptions = {
  "Primary Fence": [
    {
      name: "Pearl",
      hex: "#E3E6D5",
    },
    { name: "Meriot", hex: "#821B21" },
    {
      name: "Steel Blue",
      hex: "#3B4750",
    },
    {
      name: "Deep Blue",
      hex: "#0D3A66",
    },
    {
      name: "Charcoal",
      hex: "#424142",
    },
    {
      name: "Midnight Black",
      hex: "#000000",
    },
  ],
  "Secondary Fence": [
    {
      name: "Pearl",
      hex: "#E3E6D5",
    },
    { name: "Meriot", hex: "#821B21" },
    {
      name: "Steel Blue",
      hex: "#3B4750",
    },
    {
      name: "Deep Blue",
      hex: "#0D3A66",
    },
    {
      name: "Charcoal",
      hex: "#424142",
    },
    {
      name: "Midnight Black",
      hex: "#000000",
    },
  ],
  "Exterior Rail": [
    {
      name: "Metal",
      hex: "#D5E2E6",
    },
    {
      name: "Midnight Black",
      hex: "#000000",
    },
  ],
  "Interior Options": [
    {
      name: "Taupe Series",
      hex: "#B8AB9E",
    },
    {
      name: "Grey Series",
      hex: "#d1d1d1",
    },
    
  ],
};

export const secondaryInteriorColorCodes = {
  "#B8AB9E": "#998a7a",
  "#d1d1d1": "#454545",
  
};

export const variants = {
  "Island Breeze 172 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["ib172_FP.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        { name: "Atlantis Deck Upgrade", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Chrome Light Housing w/ Dock Side Lights (CRS)", price: 85 },
        { name: "Chrome Light Housing w/ Dock Side Lights (SC)", price: 85 },
        {
          name: "Exchange Chrome for Smoked Chrome Light Housing (For Black Rails)",
          price: 185,
        },
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "Docking Lights", price: 165 },
        { name: "GPS Speedo", price: 165 },
        { name: "Hour Meter", price: 165 },
        { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
        { name: "In Dash Depth Gauge", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lighting (Transom)", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "Courtesy Light on Console", price: 165 },
        { name: "Trim Gauge Honda", price: 165 },
        { name: "Trim Gauge Mercury", price: 165 },
        { name: "Trim Gauge Yamaha", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Flint Grey", price: 495 },
        { name: "Interior Package - Taupe", price: 495 },
        {
          name: "Interior Package - Cognac (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        {
          name: "Interior Package - Anthracite (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        { name: "Fish Rear Seating", price: 575 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
        { name: "Upgrade Fish Chair to IB Capt. Chair (SC/IB192)", price: 575 },
        {
          name: "Upgrade IB Capt. Chair for Signature Bolster Chair",
          price: 575,
        },
        {
          name: "Upgrade IB Capt. Chair for Signature Leg Lift Chair",
          price: 575,
        },
        { name: "Exchange 45' Couch for Chaise & 30' Couch", price: 495 },
        { name: "Exchange 60' Couch for Chaise & 45' Couch", price: 495 },
        { name: "Trash Receiver (Req. Chaise Lounge)", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal", price: 495 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        {
          name: "Wake Board Tower - Split Rear or Sport Rear (Must have Atlantis Deck)",
          price: 90,
        },
        { name: "Cleats - Exchange Std for Fold Down (2 pr)", price: 375 },
        { name: "Cleats - Exchange Std for Pull Up (2 pr)", price: 375 },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Port Rail Cup Holder", price: 475 },
        { name: "Tilt Steering (STD w/ Hydraulic Steering)", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Ladder Upgrade to Atlantis", price: 375 },
        { name: "Ladder Upgrade to Signature", price: 375 },
        {
          name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
          price: 375,
        },
        { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
        { name: "Table Complete - Oval - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
  "Island Breeze 192 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["ib192_FP.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes", price: 750 },
        { name: "Full Spray Shield for Tri-Log", price: 750 },
        { name: "Spray Shield 3/4 (2-Log)", price: 750 },
        { name: "Spray Shield Full (2-Log)", price: 750 },
        { name: "Atlantis Deck Upgrade", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Chrome Light Housing w/ Dock Side Lights (CRS)", price: 85 },
        { name: "Chrome Light Housing w/ Dock Side Lights (SC)", price: 85 },
        {
          name: "Exchange Chrome for Smoked Chrome Light Housing (For Black Rails)",
          price: 185,
        },
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "Docking Lights", price: 165 },
        { name: "GPS Speedo", price: 165 },
        { name: "Hour Meter", price: 165 },
        { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
        { name: "In Dash Depth Gauge", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lighting (Transom)", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "Courtesy Light on Console", price: 165 },
        { name: "Trim Gauge Honda", price: 165 },
        { name: "Trim Gauge Mercury", price: 165 },
        { name: "Trim Gauge Yamaha", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Flint Grey", price: 495 },
        { name: "Interior Package - Taupe", price: 495 },
        {
          name: "Interior Package - Cognac (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        {
          name: "Interior Package - Anthracite (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        { name: "Fish Rear Seating", price: 575 },
        { name: "Sport Rear", price: 750 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
        { name: "Upgrade Fish Chair to IB Capt. Chair (SC/IB192)", price: 575 },
        {
          name: "Upgrade IB Capt. Chair for Signature Bolster Chair",
          price: 575,
        },
        {
          name: "Upgrade IB Capt. Chair for Signature Leg Lift Chair",
          price: 575,
        },
        { name: "Exchange Front Seating & Rail for 212C", price: 575 },
        { name: "Exchange 45' Couch for Chaise & 30' Couch", price: 495 },
        { name: "Exchange 60' Couch for Chaise & 45' Couch", price: 495 },
        { name: "Trash Receiver (Req. Chaise Lounge)", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal", price: 495 },
        { name: "Sport Cruise Seating (Fish Seats Up Front)", price: 750 },
        { name: "Upgrade 192 to Island Breeze Console", price: 750 },
        {
          name: "Upgrade IB to ATL Console 7' Simrad & Touch Screen Gauges",
          price: 750,
        },
        { name: "Remove IB Console & Install 192 Console", price: 750 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        {
          name: "Wake Board Tower - Split Rear or Sport Rear (Must have Atlantis Deck)",
          price: 90,
        },
        { name: "Cleats - Exchange Std for Fold Down (2 pr)", price: 375 },
        { name: "Cleats - Exchange Std for Pull Up (2 pr)", price: 375 },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Port Rail Cup Holder", price: 475 },
        { name: "Tilt Steering (STD w/ Hydraulic Steering)", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Ladder Upgrade to Atlantis", price: 375 },
        { name: "Ladder Upgrade to Signature", price: 375 },
        {
          name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
          price: 375,
        },
        { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
        { name: "Table Complete - Oval - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
  "Island Breeze 212 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["ib212_FP.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Upgrade Brutus Logs/Tri", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        {
          name: "HHP Tag Brutus(Incl. Lifting Strakes, Hydl Steering) Requires Brutus Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes", price: 750 },
        { name: "Full Spray Shield for Tri-Log", price: 750 },
        { name: "Spray Shield 3/4 (2-Log)", price: 750 },
        { name: "Spray Shield Full (2-Log)", price: 750 },
        { name: "Atlantis Deck Upgrade", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Chrome Light Housing w/ Dock Side Lights (CRS)", price: 85 },
        { name: "Chrome Light Housing w/ Dock Side Lights (SC)", price: 85 },
        {
          name: "Exchange Chrome for Smoked Chrome Light Housing (For Black Rails)",
          price: 185,
        },
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "Docking Lights", price: 165 },
        { name: "GPS Speedo", price: 165 },
        { name: "Hour Meter", price: 165 },
        { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
        { name: "In Dash Depth Gauge", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lighting (Transom)", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "Courtesy Light on Console", price: 165 },
        { name: "Trim Gauge Honda", price: 165 },
        { name: "Trim Gauge Mercury", price: 165 },
        { name: "Trim Gauge Yamaha", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Flint Grey", price: 495 },
        { name: "Interior Package - Taupe", price: 495 },
        {
          name: "Interior Package - Cognac (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        {
          name: "Interior Package - Anthracite (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        { name: "Black Painted Rails & Bimini Frame", price: 495 },
        { name: "Dressing Room Assembly", price: 495 },
        { name: "Fish Rear Seating", price: 575 },
        { name: "Rear Lounge", price: 575 },
        { name: "Sport Rear", price: 750 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Exchange 'L' Seat & Decrease SunShelf to 14'", price: 495 },
        { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
        { name: "Upgrade Fish Chair to IB Capt. Chair (SC/IB192)", price: 575 },
        { name: "Upgrade IB Capt. Chair for ATL Capt. Chair", price: 575 },
        {
          name: "Upgrade IB Capt. Chair for Signature Bolster Chair",
          price: 575,
        },
        {
          name: "Upgrade IB Capt. Chair for Signature Leg Lift Chair",
          price: 575,
        },
        { name: "Exchange 45' Couch for Chaise & 30' Couch", price: 495 },
        { name: "Exchange 60' Couch for Chaise & 45' Couch", price: 495 },
        { name: "Trash Receiver (Req. Chaise Lounge)", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal", price: 495 },
        { name: "Sport Cruise Seating (Fish Seats Up Front)", price: 750 },
        { name: "Upgrade 192 to Island Breeze Console", price: 750 },
        {
          name: "Upgrade IB to ATL Console 7' Simrad & Touch Screen Gauges",
          price: 750,
        },
        { name: "Remove IB Console & Install 192 Console", price: 750 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        {
          name: "Wake Board Tower - Split Rear or Sport Rear (Must have Atlantis Deck)",
          price: 90,
        },
        { name: "Cleats - Exchange Std for Fold Down (2 pr)", price: 375 },
        { name: "Cleats - Exchange Std for Pull Up (2 pr)", price: 375 },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Port Rail Cup Holder", price: 475 },
        { name: "Tilt Steering (STD w/ Hydraulic Steering)", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Ladder Upgrade to Atlantis", price: 375 },
        { name: "Ladder Upgrade to Signature", price: 375 },
        {
          name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
          price: 375,
        },
        { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
        { name: "Table Complete - Oval - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        {
          name: "46 Gallon Gas Tank Upgrade (Req. Tri-Log Package)",
          price: 375,
        },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
  "Island Breeze 232 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["ib232_FP.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Tri-Log Package w/ Ski Storage", price: 750 },
        { name: "Upgrade Brutus Logs/Tri", price: 750 },
        { name: "Upgrade Brutus Logs/Tri w/ Ski Storage", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        {
          name: "HHP Tag Brutus(Incl. Lifting Strakes, Hydl Steering) Requires Brutus Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes", price: 750 },
        { name: "Full Spray Shield for Tri-Log", price: 750 },
        { name: "Spray Shield 3/4 (2-Log)", price: 750 },
        { name: "Spray Shield Full (2-Log)", price: 750 },
        { name: "Atlantis Deck Upgrade", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Chrome Light Housing w/ Dock Side Lights (CRS)", price: 85 },
        { name: "Chrome Light Housing w/ Dock Side Lights (SC)", price: 85 },
        {
          name: "Exchange Chrome for Smoked Chrome Light Housing (For Black Rails)",
          price: 185,
        },
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "Docking Lights", price: 165 },
        { name: "GPS Speedo", price: 165 },
        { name: "Hour Meter", price: 165 },
        { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
        { name: "In Dash Depth Gauge", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lighting (Transom)", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "Courtesy Light on Console", price: 165 },
        { name: "Trim Gauge Honda", price: 165 },
        { name: "Trim Gauge Mercury", price: 165 },
        { name: "Trim Gauge Yamaha", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Flint Grey", price: 495 },
        { name: "Interior Package - Taupe", price: 495 },
        {
          name: "Interior Package - Cognac (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        {
          name: "Interior Package - Anthracite (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        { name: "Black Painted Rails & Bimini Frame", price: 495 },
        { name: "Dressing Room Assembly", price: 495 },
        { name: "Fish Rear Seating", price: 575 },
        { name: "Rear Lounge", price: 575 },
        { name: "Split Rear Lounge", price: 575 },
        { name: "Sport Rear", price: 750 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Swing Back Rear Lounge", price: 575 },
        {
          name: "Chaise Changing Room (Must Add Chaise Lounge Opt.)",
          price: 575,
        },
        { name: "Exchange 'L' Seat & Decrease SunShelf to 14'", price: 495 },
        { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
        { name: "Upgrade Fish Chair to IB Capt. Chair (SC/IB192)", price: 575 },
        { name: "Upgrade IB Capt. Chair for ATL Capt. Chair", price: 575 },
        {
          name: "Upgrade IB Capt. Chair for Signature Bolster Chair",
          price: 575,
        },
        {
          name: "Upgrade IB Capt. Chair for Signature Leg Lift Chair",
          price: 575,
        },
        { name: "Exchange 45' Couch for Chaise & 30' Couch", price: 495 },
        { name: "Exchange 60' Couch for Chaise & 45' Couch", price: 495 },
        { name: "Trash Receiver (Req. Chaise Lounge)", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal", price: 495 },
        { name: "Sport Cruise Seating (Fish Seats Up Front)", price: 750 },
        { name: "Upgrade 192 to Island Breeze Console", price: 750 },
        {
          name: "Upgrade IB to ATL Console 7' Simrad & Touch Screen Gauges",
          price: 750,
        },
        { name: "Remove IB Console & Install 192 Console", price: 750 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        {
          name: "Wake Board Tower - Split Rear or Sport Rear (Must have Atlantis Deck)",
          price: 90,
        },
        { name: "Cleats - Exchange Std for Fold Down (2 pr)", price: 375 },
        { name: "Cleats - Exchange Std for Pull Up (2 pr)", price: 375 },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Port Rail Cup Holder", price: 475 },
        { name: "Tilt Steering (STD w/ Hydraulic Steering)", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Ladder Upgrade to Atlantis", price: 375 },
        { name: "Ladder Upgrade to Signature", price: 375 },
        {
          name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
          price: 375,
        },
        { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
        { name: "Table Complete - Oval - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        {
          name: "46 Gallon Gas Tank Upgrade (Req. Tri-Log Package)",
          price: 375,
        },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Mooring Cover (WB Tower Option)", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
  "Island Breeze 252 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["ib252_FP.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Tri-Log Package w/ Ski Storage", price: 750 },
        { name: "Upgrade Brutus Logs/Tri", price: 750 },
        { name: "Upgrade Brutus Logs/Tri w/ Ski Storage", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        {
          name: "HHP Tag Brutus(Incl. Lifting Strakes, Hydl Steering) Requires Brutus Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes", price: 750 },
        { name: "Full Spray Shield for Tri-Log", price: 750 },
        { name: "Spray Shield 3/4 (2-Log)", price: 750 },
        { name: "Spray Shield Full (2-Log)", price: 750 },
        { name: "Atlantis Deck Upgrade", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Chrome Light Housing w/ Dock Side Lights (CRS)", price: 85 },
        { name: "Chrome Light Housing w/ Dock Side Lights (SC)", price: 85 },
        {
          name: "Exchange Chrome for Smoked Chrome Light Housing (For Black Rails)",
          price: 185,
        },
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "Docking Lights", price: 165 },
        { name: "GPS Speedo", price: 165 },
        { name: "Hour Meter", price: 165 },
        { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
        { name: "In Dash Depth Gauge", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lighting (Transom)", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "Courtesy Light on Console", price: 165 },
        { name: "Trim Gauge Honda", price: 165 },
        { name: "Trim Gauge Mercury", price: 165 },
        { name: "Trim Gauge Yamaha", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Flint Grey", price: 495 },
        { name: "Interior Package - Taupe", price: 495 },
        {
          name: "Interior Package - Cognac (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        {
          name: "Interior Package - Anthracite (Cool Technology) - Must upgrade to Atlantis Capt. Chair (2)",
          price: 495,
        },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        { name: "Black Painted Rails & Bimini Frame", price: 495 },
        { name: "Dressing Room Assembly", price: 495 },
        { name: "Fish Rear Seating", price: 575 },
        { name: "Rear Lounge", price: 575 },
        { name: "Split Rear Lounge", price: 575 },
        { name: "Sport Rear", price: 750 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Swing Back Rear Lounge", price: 575 },
        {
          name: "Chaise Changing Room (Must Add Chaise Lounge Opt.)",
          price: 575,
        },
        { name: "Exchange 'L' Seat & Decrease SunShelf to 14'", price: 495 },
        { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
        { name: "Upgrade Fish Chair to IB Capt. Chair (SC/IB192)", price: 575 },
        { name: "Upgrade IB Capt. Chair for ATL Capt. Chair", price: 575 },
        {
          name: "Upgrade IB Capt. Chair for Signature Bolster Chair",
          price: 575,
        },
        {
          name: "Upgrade IB Capt. Chair for Signature Leg Lift Chair",
          price: 575,
        },
        { name: "Exchange 45' Couch for Chaise & 30' Couch", price: 495 },
        { name: "Exchange 60' Couch for Chaise & 45' Couch", price: 495 },
        { name: "Trash Receiver (Req. Chaise Lounge)", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal", price: 495 },
        { name: "Sport Cruise Seating (Fish Seats Up Front)", price: 750 },
        { name: "Upgrade 192 to Island Breeze Console", price: 750 },
        {
          name: "Upgrade IB to ATL Console 7' Simrad & Touch Screen Gauges",
          price: 750,
        },
        { name: "Remove IB Console & Install 192 Console", price: 750 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        {
          name: "Wake Board Tower - Split Rear or Sport Rear (Must have Atlantis Deck)",
          price: 90,
        },
        { name: "Cleats - Exchange Std for Fold Down (2 pr)", price: 375 },
        { name: "Cleats - Exchange Std for Pull Up (2 pr)", price: 375 },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Port Rail Cup Holder", price: 475 },
        { name: "Tilt Steering (STD w/ Hydraulic Steering)", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Ladder Upgrade to Atlantis", price: 375 },
        { name: "Ladder Upgrade to Signature", price: 375 },
        {
          name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
          price: 375,
        },
        { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
        { name: "Table Complete - Oval - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        {
          name: "46 Gallon Gas Tank Upgrade (Req. Tri-Log Package)",
          price: 375,
        },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Mooring Cover (WB Tower Option)", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
        { name: "Twin Bimini with Tower", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
};
