import img1 from "../assets/carbonFiber/carbonFiber1.jpg";
import img2 from "../assets/carbonFiber/carbonFiber2.jpg";
import img3 from "../assets/carbonFiber/carbonFiber3.jpg";

export const modelParts = ["Base Body", "Top Deck", "Deck Strip", "Interior"];
export const initialColors = {
  "Base Body": "#0D3A66",
  "Top Deck": "#E3E6D5",
  "Deck Strip": "#E3E6D5",
  Interior: "#d1d1d1",
};



export const colorTypes = [
  ["normal", "metallic"],
  ["normal", "metallic"],
  ["none", "normal", "metallic", "carbonFiber"],
  ["normal", "metallic", "carbonFiber"],
];
export const carbonFiberOptions = {
  "Base Body": [],
  "Top Deck": [],
  "Deck Strip": [
    {
      img: "/textures/carbon-fiber/1.png",
      name: "Carbon Fiber",
      textureSrc: "/textures/carbon-fiber/1.png",
    },
    // {
    //   img: img2,
    //   name: "Stripes Fiber",
    //   textureSrc: "/textures/carbon-fiber/1.png",
    // },
    // {
    //   img: img3,
    //   name: "Check Fiber",
    //   textureSrc: "/textures/carbon-fiber/1.png",
    // },
  ],
  Interior: [
    {
      img: "/textures/carbon-fiber/1.png",
      name: "Carbon  Fiber",
      textureSrc: "/textures/carbon-fiber/1.png",
    },
    // {
    //   img: img2,
    //   name: "Stripes Fiber",
    //   textureSrc: "/textures/carbon-fiber/1.png",
    // },
    // {
    //   img: img1,
    //   name: "Hexacon Fiber",
    //   textureSrc: "/textures/carbon-fiber/1.png",
    // },
  ],
};

export const metallicColorOptions = {
  "Base Body": [
    { name: "Soft Pink", hex: "#EE91C4" },
    { name: "Hot Pink", hex: "#D05DA9" },
    { name: "Bright Red Orange", hex: "#DC4017" },
    { name: "International Orange", hex: "#D22313" },
    { name: "Vermillion", hex: "#B61E11" },
    { name: "Rochelle Red", hex: "#95160F" },
    { name: "Tornado Red", hex: "#94170F" },
    { name: "Sunfast Red", hex: "#84160F" },
    { name: "Vivid Red", hex: "#721011" },
    { name: "Claret", hex: "#321717" },
    { name: "Red Mahogany", hex: "#241616" },
    { name: "Cabernet Burgundy", hex: "#281516" },
    { name: "Catboat Tan", hex: "#805D34" },
    { name: "Sahara Tan", hex: "#664A2E" },
    { name: "Horizons Teak", hex: "#231A13" },
    { name: "Sable Brown", hex: "#171614" },
    { name: "Mocha", hex: "#181919" },
    { name: "Sarafsa Red", hex: "#171515" },
    { name: "Fighting Lady Yellow", hex: "#EDA82C" },
    { name: "San Mateo Wheat", hex: "#F8AF2E" },
    { name: "Yellow", hex: "#EDBF35" },
    { name: "Lemon Yellow", hex: "#F1C937" },
    { name: "Federal Yellow", hex: "#E5E899" },
    { name: "Saffron Yellow", hex: "#D7CE8C" },
    { name: "Citrus", hex: "#B5D041" },
    { name: "Lime", hex: "#76BC43" },
    { name: "Citrus Green", hex: "#43AB44" },
    { name: "Kelly Green", hex: "#162E1F" },
    { name: "Forest Green", hex: "#15201C" },
    { name: "Sea Green", hex: "#151D1B" },
    { name: "Sea Foam", hex: "#97E0E5" },
    { name: "Boston Whaler Blue", hex: "#31A9D6" },
    { name: "Island Turquoise", hex: "#156D8A" },
    { name: "Teal", hex: "#0D354F" },
    { name: "Brightside Teal", hex: "#11262E" },
    { name: "Travel Lift Blue", hex: "#163043" },
    { name: "Petrol Blue", hex: "#18304B" },
    { name: "Stars & Stripes Blue", hex: "#1E3C5C" },
    { name: "Pigeon Blue", hex: "#274470" },
    { name: "Light Blue", hex: "#A2E6FA" },
    { name: "Sky Blue", hex: "#4299D0" },
    { name: "Bahama Blue", hex: "#1A66A6" },
    { name: "Empress Blue", hex: "#0D499B" },
    { name: "Marlin Blue", hex: "#093E88" },
    { name: "Ocean Blue", hex: "#0C2D5F" },
    { name: "Largo Blue", hex: "#0C307C" },
    { name: "Lauderdale Blue", hex: "#0E2E76" },
    { name: "Navy Blue", hex: "#10255E" },
    { name: "Royal Blue", hex: "#101C3F" },
    { name: "Aristo Blue", hex: "#171D2B" },
    { name: "Carinthia Blue", hex: "#141619" },
    { name: "Flag Blue", hex: "#111415" },
    { name: "Dark Blue", hex: "#16181A" },
    { name: "Mauritius Blue", hex: "#1B212E" },
    { name: "Jade Mist Green", hex: "#141C1A" },
    { name: "Donegal Green", hex: "#161A18" },
    { name: "Dark Green", hex: "#121515" },
    { name: "Timeless Green", hex: "#111313" },
    { name: "Majestic Blue", hex: "#131415" },
    { name: "Midnight Blue", hex: "#171C20" },
    { name: "Bertram White", hex: "#F8FAEB" },
    { name: "Sand White", hex: "#F7FAED" },
    { name: "Chalky White", hex: "#EFF7E7" },
    { name: "Morrinsville Double", hex: "#F0F7E5" },
    { name: "Cream", hex: "#E2EFDF" },
    { name: "Lunar White", hex: "#D5D8C8" },
    { name: "Hatteras Off-White", hex: "#F7F9EA" },
    { name: "Hatteras Off-White 4208", hex: "#F1F6DF" },
    { name: "Biscuit", hex: "#E6F0CF" },
    { name: "Light Ivory", hex: "#E5EEC1" },
    { name: "Moon Dust", hex: "#CFD9B2" },
    { name: "Desert Tan", hex: "#A8BA9E" },
    { name: "Grand Banks Beige", hex: "#BBB18B" },
    { name: "Grand Banks Beige 4217", hex: "#97A281" },
    { name: "Desert Sand", hex: "#9A9769" },
    { name: "Castle Tan", hex: "#90865F" },
    { name: "Prairie Beige", hex: "#AB7D3C" },
    { name: "Bristol Beige", hex: "#DDBF81" },
    { name: "Pale Gold", hex: "#634927" },
    { name: "Cordovan Gold", hex: "#594D17" },
    { name: "Bronze", hex: "#1E1B18" },
    { name: "Super Jet Black", hex: "#121413" },
    { name: "Shark", hex: "#1E2020" },
    { name: "Anthracite Gray", hex: "#141717" },
    { name: "Dark Gray", hex: "#31444A" },
    { name: "Haze Gray", hex: "#465156" },
    { name: "Medium Gray", hex: "#50646D" },
    { name: "Silver", hex: "#606D6C" },
    { name: "Medium Silver", hex: "#91A4A5" },
    { name: "Bright Aluminum", hex: "#95ABAC" },
    { name: "Snow White Revisited", hex: "#F9FDFF" },
    { name: "Blue Glo White", hex: "#F5FBF6" },
    { name: "Clipper White", hex: "#F4FBF9" },
    { name: "Snow White", hex: "#F6FCFE" },
    { name: "Cloud White", hex: "#F4FCFE" },
    { name: "Signal White", hex: "#F1FBFC" },
    { name: "Blanc Pur", hex: "#F7FAEF" },
    { name: "Oyster White", hex: "#F7F9EA" },
    { name: "Off White", hex: "#F3F9F4" },
    { name: "Stark White", hex: "#F6FAF4" },
    { name: "Insignia White", hex: "#F5FAF4" },
    { name: "Fleet White", hex: "#EFF9F3" },
    { name: "Silver White", hex: "#E4F2E7" },
    { name: "Brightside Off-White", hex: "#F4F9EB" },
    { name: "Vanila White", hex: "#F3F8E3" },
    { name: "Egg Shell White", hex: "#F1F8EC" },
    { name: "Nordic White", hex: "#CFD4C1" },
    { name: "Graystone", hex: "#E5F1DA" },
    { name: "Off-White Revisited", hex: "#E6F5EB" },
    { name: "Matterhorn White", hex: "#E9F5F1" },
    { name: "Vestal White", hex: "#ECF8F4" },
    { name: "Blue Tone White", hex: "#E1F5F5" },
    { name: "Ice Blue", hex: "#D8F4FC" },
    { name: "Aqua Mist", hex: "#D4F2F4" },
    { name: "Kingston Gray", hex: "#A3AFAC" },
    { name: "Light Gray", hex: "#B2B7AC" },
    { name: "Seattle Gray", hex: "#BFCCBD" },
    { name: "Pearl Gray", hex: "#C5CEC5" },
    { name: "Whisper Gray", hex: "#BFCED0" },
    { name: "Chevy Gray", hex: "#DCE9E8" },
  ],
  "Top Deck": [
    { name: "Soft Pink", hex: "#EE91C4" },
    { name: "Hot Pink", hex: "#D05DA9" },
    { name: "Bright Red Orange", hex: "#DC4017" },
    { name: "International Orange", hex: "#D22313" },
    { name: "Vermillion", hex: "#B61E11" },
    { name: "Rochelle Red", hex: "#95160F" },
    { name: "Tornado Red", hex: "#94170F" },
    { name: "Sunfast Red", hex: "#84160F" },
    { name: "Vivid Red", hex: "#721011" },
    { name: "Claret", hex: "#321717" },
    { name: "Red Mahogany", hex: "#241616" },
    { name: "Cabernet Burgundy", hex: "#281516" },
    { name: "Catboat Tan", hex: "#805D34" },
    { name: "Sahara Tan", hex: "#664A2E" },
    { name: "Horizons Teak", hex: "#231A13" },
    { name: "Sable Brown", hex: "#171614" },
    { name: "Mocha", hex: "#181919" },
    { name: "Sarafsa Red", hex: "#171515" },
    { name: "Fighting Lady Yellow", hex: "#EDA82C" },
    { name: "San Mateo Wheat", hex: "#F8AF2E" },
    { name: "Yellow", hex: "#EDBF35" },
    { name: "Lemon Yellow", hex: "#F1C937" },
    { name: "Federal Yellow", hex: "#E5E899" },
    { name: "Saffron Yellow", hex: "#D7CE8C" },
    { name: "Citrus", hex: "#B5D041" },
    { name: "Lime", hex: "#76BC43" },
    { name: "Citrus Green", hex: "#43AB44" },
    { name: "Kelly Green", hex: "#162E1F" },
    { name: "Forest Green", hex: "#15201C" },
    { name: "Sea Green", hex: "#151D1B" },
    { name: "Sea Foam", hex: "#97E0E5" },
    { name: "Boston Whaler Blue", hex: "#31A9D6" },
    { name: "Island Turquoise", hex: "#156D8A" },
    { name: "Teal", hex: "#0D354F" },
    { name: "Brightside Teal", hex: "#11262E" },
    { name: "Travel Lift Blue", hex: "#163043" },
    { name: "Petrol Blue", hex: "#18304B" },
    { name: "Stars & Stripes Blue", hex: "#1E3C5C" },
    { name: "Pigeon Blue", hex: "#274470" },
    { name: "Light Blue", hex: "#A2E6FA" },
    { name: "Sky Blue", hex: "#4299D0" },
    { name: "Bahama Blue", hex: "#1A66A6" },
    { name: "Empress Blue", hex: "#0D499B" },
    { name: "Marlin Blue", hex: "#093E88" },
    { name: "Ocean Blue", hex: "#0C2D5F" },
    { name: "Largo Blue", hex: "#0C307C" },
    { name: "Lauderdale Blue", hex: "#0E2E76" },
    { name: "Navy Blue", hex: "#10255E" },
    { name: "Royal Blue", hex: "#101C3F" },
    { name: "Aristo Blue", hex: "#171D2B" },
    { name: "Carinthia Blue", hex: "#141619" },
    { name: "Flag Blue", hex: "#111415" },
    { name: "Dark Blue", hex: "#16181A" },
    { name: "Mauritius Blue", hex: "#1B212E" },
    { name: "Jade Mist Green", hex: "#141C1A" },
    { name: "Donegal Green", hex: "#161A18" },
    { name: "Dark Green", hex: "#121515" },
    { name: "Timeless Green", hex: "#111313" },
    { name: "Majestic Blue", hex: "#131415" },
    { name: "Midnight Blue", hex: "#171C20" },
    { name: "Bertram White", hex: "#F8FAEB" },
    { name: "Sand White", hex: "#F7FAED" },
    { name: "Chalky White", hex: "#EFF7E7" },
    { name: "Morrinsville Double", hex: "#F0F7E5" },
    { name: "Cream", hex: "#E2EFDF" },
    { name: "Lunar White", hex: "#D5D8C8" },
    { name: "Hatteras Off-White", hex: "#F7F9EA" },
    { name: "Hatteras Off-White 4208", hex: "#F1F6DF" },
    { name: "Biscuit", hex: "#E6F0CF" },
    { name: "Light Ivory", hex: "#E5EEC1" },
    { name: "Moon Dust", hex: "#CFD9B2" },
    { name: "Desert Tan", hex: "#A8BA9E" },
    { name: "Grand Banks Beige", hex: "#BBB18B" },
    { name: "Grand Banks Beige 4217", hex: "#97A281" },
    { name: "Desert Sand", hex: "#9A9769" },
    { name: "Castle Tan", hex: "#90865F" },
    { name: "Prairie Beige", hex: "#AB7D3C" },
    { name: "Bristol Beige", hex: "#DDBF81" },
    { name: "Pale Gold", hex: "#634927" },
    { name: "Cordovan Gold", hex: "#594D17" },
    { name: "Bronze", hex: "#1E1B18" },
    { name: "Super Jet Black", hex: "#121413" },
    { name: "Shark", hex: "#1E2020" },
    { name: "Anthracite Gray", hex: "#141717" },
    { name: "Dark Gray", hex: "#31444A" },
    { name: "Haze Gray", hex: "#465156" },
    { name: "Medium Gray", hex: "#50646D" },
    { name: "Silver", hex: "#606D6C" },
    { name: "Medium Silver", hex: "#91A4A5" },
    { name: "Bright Aluminum", hex: "#95ABAC" },
    { name: "Snow White Revisited", hex: "#F9FDFF" },
    { name: "Blue Glo White", hex: "#F5FBF6" },
    { name: "Clipper White", hex: "#F4FBF9" },
    { name: "Snow White", hex: "#F6FCFE" },
    { name: "Cloud White", hex: "#F4FCFE" },
    { name: "Signal White", hex: "#F1FBFC" },
    { name: "Blanc Pur", hex: "#F7FAEF" },
    { name: "Oyster White", hex: "#F7F9EA" },
    { name: "Off White", hex: "#F3F9F4" },
    { name: "Stark White", hex: "#F6FAF4" },
    { name: "Insignia White", hex: "#F5FAF4" },
    { name: "Fleet White", hex: "#EFF9F3" },
    { name: "Silver White", hex: "#E4F2E7" },
    { name: "Brightside Off-White", hex: "#F4F9EB" },
    { name: "Vanila White", hex: "#F3F8E3" },
    { name: "Egg Shell White", hex: "#F1F8EC" },
    { name: "Nordic White", hex: "#CFD4C1" },
    { name: "Graystone", hex: "#E5F1DA" },
    { name: "Off-White Revisited", hex: "#E6F5EB" },
    { name: "Matterhorn White", hex: "#E9F5F1" },
    { name: "Vestal White", hex: "#ECF8F4" },
    { name: "Blue Tone White", hex: "#E1F5F5" },
    { name: "Ice Blue", hex: "#D8F4FC" },
    { name: "Aqua Mist", hex: "#D4F2F4" },
    { name: "Kingston Gray", hex: "#A3AFAC" },
    { name: "Light Gray", hex: "#B2B7AC" },
    { name: "Seattle Gray", hex: "#BFCCBD" },
    { name: "Pearl Gray", hex: "#C5CEC5" },
    { name: "Whisper Gray", hex: "#BFCED0" },
    { name: "Chevy Gray", hex: "#DCE9E8" },
  ],
  "Deck Strip": [
    { name: "Soft Pink", hex: "#EE91C4" },
    { name: "Hot Pink", hex: "#D05DA9" },
    { name: "Bright Red Orange", hex: "#DC4017" },
    { name: "International Orange", hex: "#D22313" },
    { name: "Vermillion", hex: "#B61E11" },
    { name: "Rochelle Red", hex: "#95160F" },
    { name: "Tornado Red", hex: "#94170F" },
    { name: "Sunfast Red", hex: "#84160F" },
    { name: "Vivid Red", hex: "#721011" },
    { name: "Claret", hex: "#321717" },
    { name: "Red Mahogany", hex: "#241616" },
    { name: "Cabernet Burgundy", hex: "#281516" },
    { name: "Catboat Tan", hex: "#805D34" },
    { name: "Sahara Tan", hex: "#664A2E" },
    { name: "Horizons Teak", hex: "#231A13" },
    { name: "Sable Brown", hex: "#171614" },
    { name: "Mocha", hex: "#181919" },
    { name: "Sarafsa Red", hex: "#171515" },
    { name: "Fighting Lady Yellow", hex: "#EDA82C" },
    { name: "San Mateo Wheat", hex: "#F8AF2E" },
    { name: "Yellow", hex: "#EDBF35" },
    { name: "Lemon Yellow", hex: "#F1C937" },
    { name: "Federal Yellow", hex: "#E5E899" },
    { name: "Saffron Yellow", hex: "#D7CE8C" },
    { name: "Citrus", hex: "#B5D041" },
    { name: "Lime", hex: "#76BC43" },
    { name: "Citrus Green", hex: "#43AB44" },
    { name: "Kelly Green", hex: "#162E1F" },
    { name: "Forest Green", hex: "#15201C" },
    { name: "Sea Green", hex: "#151D1B" },
    { name: "Sea Foam", hex: "#97E0E5" },
    { name: "Boston Whaler Blue", hex: "#31A9D6" },
    { name: "Island Turquoise", hex: "#156D8A" },
    { name: "Teal", hex: "#0D354F" },
    { name: "Brightside Teal", hex: "#11262E" },
    { name: "Travel Lift Blue", hex: "#163043" },
    { name: "Petrol Blue", hex: "#18304B" },
    { name: "Stars & Stripes Blue", hex: "#1E3C5C" },
    { name: "Pigeon Blue", hex: "#274470" },
    { name: "Light Blue", hex: "#A2E6FA" },
    { name: "Sky Blue", hex: "#4299D0" },
    { name: "Bahama Blue", hex: "#1A66A6" },
    { name: "Empress Blue", hex: "#0D499B" },
    { name: "Marlin Blue", hex: "#093E88" },
    { name: "Ocean Blue", hex: "#0C2D5F" },
    { name: "Largo Blue", hex: "#0C307C" },
    { name: "Lauderdale Blue", hex: "#0E2E76" },
    { name: "Navy Blue", hex: "#10255E" },
    { name: "Royal Blue", hex: "#101C3F" },
    { name: "Aristo Blue", hex: "#171D2B" },
    { name: "Carinthia Blue", hex: "#141619" },
    { name: "Flag Blue", hex: "#111415" },
    { name: "Dark Blue", hex: "#16181A" },
    { name: "Mauritius Blue", hex: "#1B212E" },
    { name: "Jade Mist Green", hex: "#141C1A" },
    { name: "Donegal Green", hex: "#161A18" },
    { name: "Dark Green", hex: "#121515" },
    { name: "Timeless Green", hex: "#111313" },
    { name: "Majestic Blue", hex: "#131415" },
    { name: "Midnight Blue", hex: "#171C20" },
    { name: "Bertram White", hex: "#F8FAEB" },
    { name: "Sand White", hex: "#F7FAED" },
    { name: "Chalky White", hex: "#EFF7E7" },
    { name: "Morrinsville Double", hex: "#F0F7E5" },
    { name: "Cream", hex: "#E2EFDF" },
    { name: "Lunar White", hex: "#D5D8C8" },
    { name: "Hatteras Off-White", hex: "#F7F9EA" },
    { name: "Hatteras Off-White 4208", hex: "#F1F6DF" },
    { name: "Biscuit", hex: "#E6F0CF" },
    { name: "Light Ivory", hex: "#E5EEC1" },
    { name: "Moon Dust", hex: "#CFD9B2" },
    { name: "Desert Tan", hex: "#A8BA9E" },
    { name: "Grand Banks Beige", hex: "#BBB18B" },
    { name: "Grand Banks Beige 4217", hex: "#97A281" },
    { name: "Desert Sand", hex: "#9A9769" },
    { name: "Castle Tan", hex: "#90865F" },
    { name: "Prairie Beige", hex: "#AB7D3C" },
    { name: "Bristol Beige", hex: "#DDBF81" },
    { name: "Pale Gold", hex: "#634927" },
    { name: "Cordovan Gold", hex: "#594D17" },
    { name: "Bronze", hex: "#1E1B18" },
    { name: "Super Jet Black", hex: "#121413" },
    { name: "Shark", hex: "#1E2020" },
    { name: "Anthracite Gray", hex: "#141717" },
    { name: "Dark Gray", hex: "#31444A" },
    { name: "Haze Gray", hex: "#465156" },
    { name: "Medium Gray", hex: "#50646D" },
    { name: "Silver", hex: "#606D6C" },
    { name: "Medium Silver", hex: "#91A4A5" },
    { name: "Bright Aluminum", hex: "#95ABAC" },
    { name: "Snow White Revisited", hex: "#F9FDFF" },
    { name: "Blue Glo White", hex: "#F5FBF6" },
    { name: "Clipper White", hex: "#F4FBF9" },
    { name: "Snow White", hex: "#F6FCFE" },
    { name: "Cloud White", hex: "#F4FCFE" },
    { name: "Signal White", hex: "#F1FBFC" },
    { name: "Blanc Pur", hex: "#F7FAEF" },
    { name: "Oyster White", hex: "#F7F9EA" },
    { name: "Off White", hex: "#F3F9F4" },
    { name: "Stark White", hex: "#F6FAF4" },
    { name: "Insignia White", hex: "#F5FAF4" },
    { name: "Fleet White", hex: "#EFF9F3" },
    { name: "Silver White", hex: "#E4F2E7" },
    { name: "Brightside Off-White", hex: "#F4F9EB" },
    { name: "Vanila White", hex: "#F3F8E3" },
    { name: "Egg Shell White", hex: "#F1F8EC" },
    { name: "Nordic White", hex: "#CFD4C1" },
    { name: "Graystone", hex: "#E5F1DA" },
    { name: "Off-White Revisited", hex: "#E6F5EB" },
    { name: "Matterhorn White", hex: "#E9F5F1" },
    { name: "Vestal White", hex: "#ECF8F4" },
    { name: "Blue Tone White", hex: "#E1F5F5" },
    { name: "Ice Blue", hex: "#D8F4FC" },
    { name: "Aqua Mist", hex: "#D4F2F4" },
    { name: "Kingston Gray", hex: "#A3AFAC" },
    { name: "Light Gray", hex: "#B2B7AC" },
    { name: "Seattle Gray", hex: "#BFCCBD" },
    { name: "Pearl Gray", hex: "#C5CEC5" },
    { name: "Whisper Gray", hex: "#BFCED0" },
    { name: "Chevy Gray", hex: "#DCE9E8" },
  ],
  Interior: [
    { name: "Soft Pink", hex: "#EE91C4" },
    { name: "Hot Pink", hex: "#D05DA9" },
    { name: "Bright Red Orange", hex: "#DC4017" },
    { name: "International Orange", hex: "#D22313" },
    { name: "Vermillion", hex: "#B61E11" },
    { name: "Rochelle Red", hex: "#95160F" },
    { name: "Tornado Red", hex: "#94170F" },
    { name: "Sunfast Red", hex: "#84160F" },
    { name: "Vivid Red", hex: "#721011" },
    { name: "Claret", hex: "#321717" },
    { name: "Red Mahogany", hex: "#241616" },
    { name: "Cabernet Burgundy", hex: "#281516" },
    { name: "Catboat Tan", hex: "#805D34" },
    { name: "Sahara Tan", hex: "#664A2E" },
    { name: "Horizons Teak", hex: "#231A13" },
    { name: "Sable Brown", hex: "#171614" },
    { name: "Mocha", hex: "#181919" },
    { name: "Sarafsa Red", hex: "#171515" },
    { name: "Fighting Lady Yellow", hex: "#EDA82C" },
    { name: "San Mateo Wheat", hex: "#F8AF2E" },
    { name: "Yellow", hex: "#EDBF35" },
    { name: "Lemon Yellow", hex: "#F1C937" },
    { name: "Federal Yellow", hex: "#E5E899" },
    { name: "Saffron Yellow", hex: "#D7CE8C" },
    { name: "Citrus", hex: "#B5D041" },
    { name: "Lime", hex: "#76BC43" },
    { name: "Citrus Green", hex: "#43AB44" },
    { name: "Kelly Green", hex: "#162E1F" },
    { name: "Forest Green", hex: "#15201C" },
    { name: "Sea Green", hex: "#151D1B" },
    { name: "Sea Foam", hex: "#97E0E5" },
    { name: "Boston Whaler Blue", hex: "#31A9D6" },
    { name: "Island Turquoise", hex: "#156D8A" },
    { name: "Teal", hex: "#0D354F" },
    { name: "Brightside Teal", hex: "#11262E" },
    { name: "Travel Lift Blue", hex: "#163043" },
    { name: "Petrol Blue", hex: "#18304B" },
    { name: "Stars & Stripes Blue", hex: "#1E3C5C" },
    { name: "Pigeon Blue", hex: "#274470" },
    { name: "Light Blue", hex: "#A2E6FA" },
    { name: "Sky Blue", hex: "#4299D0" },
    { name: "Bahama Blue", hex: "#1A66A6" },
    { name: "Empress Blue", hex: "#0D499B" },
    { name: "Marlin Blue", hex: "#093E88" },
    { name: "Ocean Blue", hex: "#0C2D5F" },
    { name: "Largo Blue", hex: "#0C307C" },
    { name: "Lauderdale Blue", hex: "#0E2E76" },
    { name: "Navy Blue", hex: "#10255E" },
    { name: "Royal Blue", hex: "#101C3F" },
    { name: "Aristo Blue", hex: "#171D2B" },
    { name: "Carinthia Blue", hex: "#141619" },
    { name: "Flag Blue", hex: "#111415" },
    { name: "Dark Blue", hex: "#16181A" },
    { name: "Mauritius Blue", hex: "#1B212E" },
    { name: "Jade Mist Green", hex: "#141C1A" },
    { name: "Donegal Green", hex: "#161A18" },
    { name: "Dark Green", hex: "#121515" },
    { name: "Timeless Green", hex: "#111313" },
    { name: "Majestic Blue", hex: "#131415" },
    { name: "Midnight Blue", hex: "#171C20" },
    { name: "Bertram White", hex: "#F8FAEB" },
    { name: "Sand White", hex: "#F7FAED" },
    { name: "Chalky White", hex: "#EFF7E7" },
    { name: "Morrinsville Double", hex: "#F0F7E5" },
    { name: "Cream", hex: "#E2EFDF" },
    { name: "Lunar White", hex: "#D5D8C8" },
    { name: "Hatteras Off-White", hex: "#F7F9EA" },
    { name: "Hatteras Off-White 4208", hex: "#F1F6DF" },
    { name: "Biscuit", hex: "#E6F0CF" },
    { name: "Light Ivory", hex: "#E5EEC1" },
    { name: "Moon Dust", hex: "#CFD9B2" },
    { name: "Desert Tan", hex: "#A8BA9E" },
    { name: "Grand Banks Beige", hex: "#BBB18B" },
    { name: "Grand Banks Beige 4217", hex: "#97A281" },
    { name: "Desert Sand", hex: "#9A9769" },
    { name: "Castle Tan", hex: "#90865F" },
    { name: "Prairie Beige", hex: "#AB7D3C" },
    { name: "Bristol Beige", hex: "#DDBF81" },
    { name: "Pale Gold", hex: "#634927" },
    { name: "Cordovan Gold", hex: "#594D17" },
    { name: "Bronze", hex: "#1E1B18" },
    { name: "Super Jet Black", hex: "#121413" },
    { name: "Shark", hex: "#1E2020" },
    { name: "Anthracite Gray", hex: "#141717" },
    { name: "Dark Gray", hex: "#31444A" },
    { name: "Haze Gray", hex: "#465156" },
    { name: "Medium Gray", hex: "#50646D" },
    { name: "Silver", hex: "#606D6C" },
    { name: "Medium Silver", hex: "#91A4A5" },
    { name: "Bright Aluminum", hex: "#95ABAC" },
    { name: "Snow White Revisited", hex: "#F9FDFF" },
    { name: "Blue Glo White", hex: "#F5FBF6" },
    { name: "Clipper White", hex: "#F4FBF9" },
    { name: "Snow White", hex: "#F6FCFE" },
    { name: "Cloud White", hex: "#F4FCFE" },
    { name: "Signal White", hex: "#F1FBFC" },
    { name: "Blanc Pur", hex: "#F7FAEF" },
    { name: "Oyster White", hex: "#F7F9EA" },
    { name: "Off White", hex: "#F3F9F4" },
    { name: "Stark White", hex: "#F6FAF4" },
    { name: "Insignia White", hex: "#F5FAF4" },
    { name: "Fleet White", hex: "#EFF9F3" },
    { name: "Silver White", hex: "#E4F2E7" },
    { name: "Brightside Off-White", hex: "#F4F9EB" },
    { name: "Vanila White", hex: "#F3F8E3" },
    { name: "Egg Shell White", hex: "#F1F8EC" },
    { name: "Nordic White", hex: "#CFD4C1" },
    { name: "Graystone", hex: "#E5F1DA" },
    { name: "Off-White Revisited", hex: "#E6F5EB" },
    { name: "Matterhorn White", hex: "#E9F5F1" },
    { name: "Vestal White", hex: "#ECF8F4" },
    { name: "Blue Tone White", hex: "#E1F5F5" },
    { name: "Ice Blue", hex: "#D8F4FC" },
    { name: "Aqua Mist", hex: "#D4F2F4" },
    { name: "Kingston Gray", hex: "#A3AFAC" },
    { name: "Light Gray", hex: "#B2B7AC" },
    { name: "Seattle Gray", hex: "#BFCCBD" },
    { name: "Pearl Gray", hex: "#C5CEC5" },
    { name: "Whisper Gray", hex: "#BFCED0" },
    { name: "Chevy Gray", hex: "#DCE9E8" },
  ],
};

export const colorOptions = {
  "Base Body": [
    { name: "Soft Pink", hex: "#EE91C4" },
    { name: "Hot Pink", hex: "#D05DA9" },
    { name: "Bright Red Orange", hex: "#DC4017" },
    { name: "International Orange", hex: "#D22313" },
    { name: "Vermillion", hex: "#B61E11" },
    { name: "Rochelle Red", hex: "#95160F" },
    { name: "Tornado Red", hex: "#94170F" },
    { name: "Sunfast Red", hex: "#84160F" },
    { name: "Vivid Red", hex: "#721011" },
    { name: "Claret", hex: "#321717" },
    { name: "Red Mahogany", hex: "#241616" },
    { name: "Cabernet Burgundy", hex: "#281516" },
    { name: "Catboat Tan", hex: "#805D34" },
    { name: "Sahara Tan", hex: "#664A2E" },
    { name: "Horizons Teak", hex: "#231A13" },
    { name: "Sable Brown", hex: "#171614" },
    { name: "Mocha", hex: "#181919" },
    { name: "Sarafsa Red", hex: "#171515" },
    { name: "Fighting Lady Yellow", hex: "#EDA82C" },
    { name: "San Mateo Wheat", hex: "#F8AF2E" },
    { name: "Yellow", hex: "#EDBF35" },
    { name: "Lemon Yellow", hex: "#F1C937" },
    { name: "Federal Yellow", hex: "#E5E899" },
    { name: "Saffron Yellow", hex: "#D7CE8C" },
    { name: "Citrus", hex: "#B5D041" },
    { name: "Lime", hex: "#76BC43" },
    { name: "Citrus Green", hex: "#43AB44" },
    { name: "Kelly Green", hex: "#162E1F" },
    { name: "Forest Green", hex: "#15201C" },
    { name: "Sea Green", hex: "#151D1B" },
    { name: "Sea Foam", hex: "#97E0E5" },
    { name: "Boston Whaler Blue", hex: "#31A9D6" },
    { name: "Island Turquoise", hex: "#156D8A" },
    { name: "Teal", hex: "#0D354F" },
    { name: "Brightside Teal", hex: "#11262E" },
    { name: "Travel Lift Blue", hex: "#163043" },
    { name: "Petrol Blue", hex: "#18304B" },
    { name: "Stars & Stripes Blue", hex: "#1E3C5C" },
    { name: "Pigeon Blue", hex: "#274470" },
    { name: "Light Blue", hex: "#A2E6FA" },
    { name: "Sky Blue", hex: "#4299D0" },
    { name: "Bahama Blue", hex: "#1A66A6" },
    { name: "Empress Blue", hex: "#0D499B" },
    { name: "Marlin Blue", hex: "#093E88" },
    { name: "Ocean Blue", hex: "#0C2D5F" },
    { name: "Largo Blue", hex: "#0C307C" },
    { name: "Lauderdale Blue", hex: "#0E2E76" },
    { name: "Navy Blue", hex: "#10255E" },
    { name: "Royal Blue", hex: "#101C3F" },
    { name: "Aristo Blue", hex: "#171D2B" },
    { name: "Carinthia Blue", hex: "#141619" },
    { name: "Flag Blue", hex: "#111415" },
    { name: "Dark Blue", hex: "#16181A" },
    { name: "Mauritius Blue", hex: "#1B212E" },
    { name: "Jade Mist Green", hex: "#141C1A" },
    { name: "Donegal Green", hex: "#161A18" },
    { name: "Dark Green", hex: "#121515" },
    { name: "Timeless Green", hex: "#111313" },
    { name: "Majestic Blue", hex: "#131415" },
    { name: "Midnight Blue", hex: "#171C20" },
    { name: "Bertram White", hex: "#F8FAEB" },
    { name: "Sand White", hex: "#F7FAED" },
    { name: "Chalky White", hex: "#EFF7E7" },
    { name: "Morrinsville Double", hex: "#F0F7E5" },
    { name: "Cream", hex: "#E2EFDF" },
    { name: "Lunar White", hex: "#D5D8C8" },
    { name: "Hatteras Off-White", hex: "#F7F9EA" },
    { name: "Hatteras Off-White 4208", hex: "#F1F6DF" },
    { name: "Biscuit", hex: "#E6F0CF" },
    { name: "Light Ivory", hex: "#E5EEC1" },
    { name: "Moon Dust", hex: "#CFD9B2" },
    { name: "Desert Tan", hex: "#A8BA9E" },
    { name: "Grand Banks Beige", hex: "#BBB18B" },
    { name: "Grand Banks Beige 4217", hex: "#97A281" },
    { name: "Desert Sand", hex: "#9A9769" },
    { name: "Castle Tan", hex: "#90865F" },
    { name: "Prairie Beige", hex: "#AB7D3C" },
    { name: "Bristol Beige", hex: "#DDBF81" },
    { name: "Pale Gold", hex: "#634927" },
    { name: "Cordovan Gold", hex: "#594D17" },
    { name: "Bronze", hex: "#1E1B18" },
    { name: "Super Jet Black", hex: "#121413" },
    { name: "Shark", hex: "#1E2020" },
    { name: "Anthracite Gray", hex: "#141717" },
    { name: "Dark Gray", hex: "#31444A" },
    { name: "Haze Gray", hex: "#465156" },
    { name: "Medium Gray", hex: "#50646D" },
    { name: "Silver", hex: "#606D6C" },
    { name: "Medium Silver", hex: "#91A4A5" },
    { name: "Bright Aluminum", hex: "#95ABAC" },
    { name: "Snow White Revisited", hex: "#F9FDFF" },
    { name: "Blue Glo White", hex: "#F5FBF6" },
    { name: "Clipper White", hex: "#F4FBF9" },
    { name: "Snow White", hex: "#F6FCFE" },
    { name: "Cloud White", hex: "#F4FCFE" },
    { name: "Signal White", hex: "#F1FBFC" },
    { name: "Blanc Pur", hex: "#F7FAEF" },
    { name: "Oyster White", hex: "#F7F9EA" },
    { name: "Off White", hex: "#F3F9F4" },
    { name: "Stark White", hex: "#F6FAF4" },
    { name: "Insignia White", hex: "#F5FAF4" },
    { name: "Fleet White", hex: "#EFF9F3" },
    { name: "Silver White", hex: "#E4F2E7" },
    { name: "Brightside Off-White", hex: "#F4F9EB" },
    { name: "Vanila White", hex: "#F3F8E3" },
    { name: "Egg Shell White", hex: "#F1F8EC" },
    { name: "Nordic White", hex: "#CFD4C1" },
    { name: "Graystone", hex: "#E5F1DA" },
    { name: "Off-White Revisited", hex: "#E6F5EB" },
    { name: "Matterhorn White", hex: "#E9F5F1" },
    { name: "Vestal White", hex: "#ECF8F4" },
    { name: "Blue Tone White", hex: "#E1F5F5" },
    { name: "Ice Blue", hex: "#D8F4FC" },
    { name: "Aqua Mist", hex: "#D4F2F4" },
    { name: "Kingston Gray", hex: "#A3AFAC" },
    { name: "Light Gray", hex: "#B2B7AC" },
    { name: "Seattle Gray", hex: "#BFCCBD" },
    { name: "Pearl Gray", hex: "#C5CEC5" },
    { name: "Whisper Gray", hex: "#BFCED0" },
    { name: "Chevy Gray", hex: "#DCE9E8" },
  ],
  "Top Deck": [
    { name: "Soft Pink", hex: "#EE91C4" },
    { name: "Hot Pink", hex: "#D05DA9" },
    { name: "Bright Red Orange", hex: "#DC4017" },
    { name: "International Orange", hex: "#D22313" },
    { name: "Vermillion", hex: "#B61E11" },
    { name: "Rochelle Red", hex: "#95160F" },
    { name: "Tornado Red", hex: "#94170F" },
    { name: "Sunfast Red", hex: "#84160F" },
    { name: "Vivid Red", hex: "#721011" },
    { name: "Claret", hex: "#321717" },
    { name: "Red Mahogany", hex: "#241616" },
    { name: "Cabernet Burgundy", hex: "#281516" },
    { name: "Catboat Tan", hex: "#805D34" },
    { name: "Sahara Tan", hex: "#664A2E" },
    { name: "Horizons Teak", hex: "#231A13" },
    { name: "Sable Brown", hex: "#171614" },
    { name: "Mocha", hex: "#181919" },
    { name: "Sarafsa Red", hex: "#171515" },
    { name: "Fighting Lady Yellow", hex: "#EDA82C" },
    { name: "San Mateo Wheat", hex: "#F8AF2E" },
    { name: "Yellow", hex: "#EDBF35" },
    { name: "Lemon Yellow", hex: "#F1C937" },
    { name: "Federal Yellow", hex: "#E5E899" },
    { name: "Saffron Yellow", hex: "#D7CE8C" },
    { name: "Citrus", hex: "#B5D041" },
    { name: "Lime", hex: "#76BC43" },
    { name: "Citrus Green", hex: "#43AB44" },
    { name: "Kelly Green", hex: "#162E1F" },
    { name: "Forest Green", hex: "#15201C" },
    { name: "Sea Green", hex: "#151D1B" },
    { name: "Sea Foam", hex: "#97E0E5" },
    { name: "Boston Whaler Blue", hex: "#31A9D6" },
    { name: "Island Turquoise", hex: "#156D8A" },
    { name: "Teal", hex: "#0D354F" },
    { name: "Brightside Teal", hex: "#11262E" },
    { name: "Travel Lift Blue", hex: "#163043" },
    { name: "Petrol Blue", hex: "#18304B" },
    { name: "Stars & Stripes Blue", hex: "#1E3C5C" },
    { name: "Pigeon Blue", hex: "#274470" },
    { name: "Light Blue", hex: "#A2E6FA" },
    { name: "Sky Blue", hex: "#4299D0" },
    { name: "Bahama Blue", hex: "#1A66A6" },
    { name: "Empress Blue", hex: "#0D499B" },
    { name: "Marlin Blue", hex: "#093E88" },
    { name: "Ocean Blue", hex: "#0C2D5F" },
    { name: "Largo Blue", hex: "#0C307C" },
    { name: "Lauderdale Blue", hex: "#0E2E76" },
    { name: "Navy Blue", hex: "#10255E" },
    { name: "Royal Blue", hex: "#101C3F" },
    { name: "Aristo Blue", hex: "#171D2B" },
    { name: "Carinthia Blue", hex: "#141619" },
    { name: "Flag Blue", hex: "#111415" },
    { name: "Dark Blue", hex: "#16181A" },
    { name: "Mauritius Blue", hex: "#1B212E" },
    { name: "Jade Mist Green", hex: "#141C1A" },
    { name: "Donegal Green", hex: "#161A18" },
    { name: "Dark Green", hex: "#121515" },
    { name: "Timeless Green", hex: "#111313" },
    { name: "Majestic Blue", hex: "#131415" },
    { name: "Midnight Blue", hex: "#171C20" },
    { name: "Bertram White", hex: "#F8FAEB" },
    { name: "Sand White", hex: "#F7FAED" },
    { name: "Chalky White", hex: "#EFF7E7" },
    { name: "Morrinsville Double", hex: "#F0F7E5" },
    { name: "Cream", hex: "#E2EFDF" },
    { name: "Lunar White", hex: "#D5D8C8" },
    { name: "Hatteras Off-White", hex: "#F7F9EA" },
    { name: "Hatteras Off-White 4208", hex: "#F1F6DF" },
    { name: "Biscuit", hex: "#E6F0CF" },
    { name: "Light Ivory", hex: "#E5EEC1" },
    { name: "Moon Dust", hex: "#CFD9B2" },
    { name: "Desert Tan", hex: "#A8BA9E" },
    { name: "Grand Banks Beige", hex: "#BBB18B" },
    { name: "Grand Banks Beige 4217", hex: "#97A281" },
    { name: "Desert Sand", hex: "#9A9769" },
    { name: "Castle Tan", hex: "#90865F" },
    { name: "Prairie Beige", hex: "#AB7D3C" },
    { name: "Bristol Beige", hex: "#DDBF81" },
    { name: "Pale Gold", hex: "#634927" },
    { name: "Cordovan Gold", hex: "#594D17" },
    { name: "Bronze", hex: "#1E1B18" },
    { name: "Super Jet Black", hex: "#121413" },
    { name: "Shark", hex: "#1E2020" },
    { name: "Anthracite Gray", hex: "#141717" },
    { name: "Dark Gray", hex: "#31444A" },
    { name: "Haze Gray", hex: "#465156" },
    { name: "Medium Gray", hex: "#50646D" },
    { name: "Silver", hex: "#606D6C" },
    { name: "Medium Silver", hex: "#91A4A5" },
    { name: "Bright Aluminum", hex: "#95ABAC" },
    { name: "Snow White Revisited", hex: "#F9FDFF" },
    { name: "Blue Glo White", hex: "#F5FBF6" },
    { name: "Clipper White", hex: "#F4FBF9" },
    { name: "Snow White", hex: "#F6FCFE" },
    { name: "Cloud White", hex: "#F4FCFE" },
    { name: "Signal White", hex: "#F1FBFC" },
    { name: "Blanc Pur", hex: "#F7FAEF" },
    { name: "Oyster White", hex: "#F7F9EA" },
    { name: "Off White", hex: "#F3F9F4" },
    { name: "Stark White", hex: "#F6FAF4" },
    { name: "Insignia White", hex: "#F5FAF4" },
    { name: "Fleet White", hex: "#EFF9F3" },
    { name: "Silver White", hex: "#E4F2E7" },
    { name: "Brightside Off-White", hex: "#F4F9EB" },
    { name: "Vanila White", hex: "#F3F8E3" },
    { name: "Egg Shell White", hex: "#F1F8EC" },
    { name: "Nordic White", hex: "#CFD4C1" },
    { name: "Graystone", hex: "#E5F1DA" },
    { name: "Off-White Revisited", hex: "#E6F5EB" },
    { name: "Matterhorn White", hex: "#E9F5F1" },
    { name: "Vestal White", hex: "#ECF8F4" },
    { name: "Blue Tone White", hex: "#E1F5F5" },
    { name: "Ice Blue", hex: "#D8F4FC" },
    { name: "Aqua Mist", hex: "#D4F2F4" },
    { name: "Kingston Gray", hex: "#A3AFAC" },
    { name: "Light Gray", hex: "#B2B7AC" },
    { name: "Seattle Gray", hex: "#BFCCBD" },
    { name: "Pearl Gray", hex: "#C5CEC5" },
    { name: "Whisper Gray", hex: "#BFCED0" },
    { name: "Chevy Gray", hex: "#DCE9E8" },
  ],
  "Deck Strip": [
    { name: "Soft Pink", hex: "#EE91C4" },
    { name: "Hot Pink", hex: "#D05DA9" },
    { name: "Bright Red Orange", hex: "#DC4017" },
    { name: "International Orange", hex: "#D22313" },
    { name: "Vermillion", hex: "#B61E11" },
    { name: "Rochelle Red", hex: "#95160F" },
    { name: "Tornado Red", hex: "#94170F" },
    { name: "Sunfast Red", hex: "#84160F" },
    { name: "Vivid Red", hex: "#721011" },
    { name: "Claret", hex: "#321717" },
    { name: "Red Mahogany", hex: "#241616" },
    { name: "Cabernet Burgundy", hex: "#281516" },
    { name: "Catboat Tan", hex: "#805D34" },
    { name: "Sahara Tan", hex: "#664A2E" },
    { name: "Horizons Teak", hex: "#231A13" },
    { name: "Sable Brown", hex: "#171614" },
    { name: "Mocha", hex: "#181919" },
    { name: "Sarafsa Red", hex: "#171515" },
    { name: "Fighting Lady Yellow", hex: "#EDA82C" },
    { name: "San Mateo Wheat", hex: "#F8AF2E" },
    { name: "Yellow", hex: "#EDBF35" },
    { name: "Lemon Yellow", hex: "#F1C937" },
    { name: "Federal Yellow", hex: "#E5E899" },
    { name: "Saffron Yellow", hex: "#D7CE8C" },
    { name: "Citrus", hex: "#B5D041" },
    { name: "Lime", hex: "#76BC43" },
    { name: "Citrus Green", hex: "#43AB44" },
    { name: "Kelly Green", hex: "#162E1F" },
    { name: "Forest Green", hex: "#15201C" },
    { name: "Sea Green", hex: "#151D1B" },
    { name: "Sea Foam", hex: "#97E0E5" },
    { name: "Boston Whaler Blue", hex: "#31A9D6" },
    { name: "Island Turquoise", hex: "#156D8A" },
    { name: "Teal", hex: "#0D354F" },
    { name: "Brightside Teal", hex: "#11262E" },
    { name: "Travel Lift Blue", hex: "#163043" },
    { name: "Petrol Blue", hex: "#18304B" },
    { name: "Stars & Stripes Blue", hex: "#1E3C5C" },
    { name: "Pigeon Blue", hex: "#274470" },
    { name: "Light Blue", hex: "#A2E6FA" },
    { name: "Sky Blue", hex: "#4299D0" },
    { name: "Bahama Blue", hex: "#1A66A6" },
    { name: "Empress Blue", hex: "#0D499B" },
    { name: "Marlin Blue", hex: "#093E88" },
    { name: "Ocean Blue", hex: "#0C2D5F" },
    { name: "Largo Blue", hex: "#0C307C" },
    { name: "Lauderdale Blue", hex: "#0E2E76" },
    { name: "Navy Blue", hex: "#10255E" },
    { name: "Royal Blue", hex: "#101C3F" },
    { name: "Aristo Blue", hex: "#171D2B" },
    { name: "Carinthia Blue", hex: "#141619" },
    { name: "Flag Blue", hex: "#111415" },
    { name: "Dark Blue", hex: "#16181A" },
    { name: "Mauritius Blue", hex: "#1B212E" },
    { name: "Jade Mist Green", hex: "#141C1A" },
    { name: "Donegal Green", hex: "#161A18" },
    { name: "Dark Green", hex: "#121515" },
    { name: "Timeless Green", hex: "#111313" },
    { name: "Majestic Blue", hex: "#131415" },
    { name: "Midnight Blue", hex: "#171C20" },
    { name: "Bertram White", hex: "#F8FAEB" },
    { name: "Sand White", hex: "#F7FAED" },
    { name: "Chalky White", hex: "#EFF7E7" },
    { name: "Morrinsville Double", hex: "#F0F7E5" },
    { name: "Cream", hex: "#E2EFDF" },
    { name: "Lunar White", hex: "#D5D8C8" },
    { name: "Hatteras Off-White", hex: "#F7F9EA" },
    { name: "Hatteras Off-White 4208", hex: "#F1F6DF" },
    { name: "Biscuit", hex: "#E6F0CF" },
    { name: "Light Ivory", hex: "#E5EEC1" },
    { name: "Moon Dust", hex: "#CFD9B2" },
    { name: "Desert Tan", hex: "#A8BA9E" },
    { name: "Grand Banks Beige", hex: "#BBB18B" },
    { name: "Grand Banks Beige 4217", hex: "#97A281" },
    { name: "Desert Sand", hex: "#9A9769" },
    { name: "Castle Tan", hex: "#90865F" },
    { name: "Prairie Beige", hex: "#AB7D3C" },
    { name: "Bristol Beige", hex: "#DDBF81" },
    { name: "Pale Gold", hex: "#634927" },
    { name: "Cordovan Gold", hex: "#594D17" },
    { name: "Bronze", hex: "#1E1B18" },
    { name: "Super Jet Black", hex: "#121413" },
    { name: "Shark", hex: "#1E2020" },
    { name: "Anthracite Gray", hex: "#141717" },
    { name: "Dark Gray", hex: "#31444A" },
    { name: "Haze Gray", hex: "#465156" },
    { name: "Medium Gray", hex: "#50646D" },
    { name: "Silver", hex: "#606D6C" },
    { name: "Medium Silver", hex: "#91A4A5" },
    { name: "Bright Aluminum", hex: "#95ABAC" },
    { name: "Snow White Revisited", hex: "#F9FDFF" },
    { name: "Blue Glo White", hex: "#F5FBF6" },
    { name: "Clipper White", hex: "#F4FBF9" },
    { name: "Snow White", hex: "#F6FCFE" },
    { name: "Cloud White", hex: "#F4FCFE" },
    { name: "Signal White", hex: "#F1FBFC" },
    { name: "Blanc Pur", hex: "#F7FAEF" },
    { name: "Oyster White", hex: "#F7F9EA" },
    { name: "Off White", hex: "#F3F9F4" },
    { name: "Stark White", hex: "#F6FAF4" },
    { name: "Insignia White", hex: "#F5FAF4" },
    { name: "Fleet White", hex: "#EFF9F3" },
    { name: "Silver White", hex: "#E4F2E7" },
    { name: "Brightside Off-White", hex: "#F4F9EB" },
    { name: "Vanila White", hex: "#F3F8E3" },
    { name: "Egg Shell White", hex: "#F1F8EC" },
    { name: "Nordic White", hex: "#CFD4C1" },
    { name: "Graystone", hex: "#E5F1DA" },
    { name: "Off-White Revisited", hex: "#E6F5EB" },
    { name: "Matterhorn White", hex: "#E9F5F1" },
    { name: "Vestal White", hex: "#ECF8F4" },
    { name: "Blue Tone White", hex: "#E1F5F5" },
    { name: "Ice Blue", hex: "#D8F4FC" },
    { name: "Aqua Mist", hex: "#D4F2F4" },
    { name: "Kingston Gray", hex: "#A3AFAC" },
    { name: "Light Gray", hex: "#B2B7AC" },
    { name: "Seattle Gray", hex: "#BFCCBD" },
    { name: "Pearl Gray", hex: "#C5CEC5" },
    { name: "Whisper Gray", hex: "#BFCED0" },
    { name: "Chevy Gray", hex: "#DCE9E8" },
  ],
  Interior: [
    { name: "Soft Pink", hex: "#EE91C4" },
    { name: "Hot Pink", hex: "#D05DA9" },
    { name: "Bright Red Orange", hex: "#DC4017" },
    { name: "International Orange", hex: "#D22313" },
    { name: "Vermillion", hex: "#B61E11" },
    { name: "Rochelle Red", hex: "#95160F" },
    { name: "Tornado Red", hex: "#94170F" },
    { name: "Sunfast Red", hex: "#84160F" },
    { name: "Vivid Red", hex: "#721011" },
    { name: "Claret", hex: "#321717" },
    { name: "Red Mahogany", hex: "#241616" },
    { name: "Cabernet Burgundy", hex: "#281516" },
    { name: "Catboat Tan", hex: "#805D34" },
    { name: "Sahara Tan", hex: "#664A2E" },
    { name: "Horizons Teak", hex: "#231A13" },
    { name: "Sable Brown", hex: "#171614" },
    { name: "Mocha", hex: "#181919" },
    { name: "Sarafsa Red", hex: "#171515" },
    { name: "Fighting Lady Yellow", hex: "#EDA82C" },
    { name: "San Mateo Wheat", hex: "#F8AF2E" },
    { name: "Yellow", hex: "#EDBF35" },
    { name: "Lemon Yellow", hex: "#F1C937" },
    { name: "Federal Yellow", hex: "#E5E899" },
    { name: "Saffron Yellow", hex: "#D7CE8C" },
    { name: "Citrus", hex: "#B5D041" },
    { name: "Lime", hex: "#76BC43" },
    { name: "Citrus Green", hex: "#43AB44" },
    { name: "Kelly Green", hex: "#162E1F" },
    { name: "Forest Green", hex: "#15201C" },
    { name: "Sea Green", hex: "#151D1B" },
    { name: "Sea Foam", hex: "#97E0E5" },
    { name: "Boston Whaler Blue", hex: "#31A9D6" },
    { name: "Island Turquoise", hex: "#156D8A" },
    { name: "Teal", hex: "#0D354F" },
    { name: "Brightside Teal", hex: "#11262E" },
    { name: "Travel Lift Blue", hex: "#163043" },
    { name: "Petrol Blue", hex: "#18304B" },
    { name: "Stars & Stripes Blue", hex: "#1E3C5C" },
    { name: "Pigeon Blue", hex: "#274470" },
    { name: "Light Blue", hex: "#A2E6FA" },
    { name: "Sky Blue", hex: "#4299D0" },
    { name: "Bahama Blue", hex: "#1A66A6" },
    { name: "Empress Blue", hex: "#0D499B" },
    { name: "Marlin Blue", hex: "#093E88" },
    { name: "Ocean Blue", hex: "#0C2D5F" },
    { name: "Largo Blue", hex: "#0C307C" },
    { name: "Lauderdale Blue", hex: "#0E2E76" },
    { name: "Navy Blue", hex: "#10255E" },
    { name: "Royal Blue", hex: "#101C3F" },
    { name: "Aristo Blue", hex: "#171D2B" },
    { name: "Carinthia Blue", hex: "#141619" },
    { name: "Flag Blue", hex: "#111415" },
    { name: "Dark Blue", hex: "#16181A" },
    { name: "Mauritius Blue", hex: "#1B212E" },
    { name: "Jade Mist Green", hex: "#141C1A" },
    { name: "Donegal Green", hex: "#161A18" },
    { name: "Dark Green", hex: "#121515" },
    { name: "Timeless Green", hex: "#111313" },
    { name: "Majestic Blue", hex: "#131415" },
    { name: "Midnight Blue", hex: "#171C20" },
    { name: "Bertram White", hex: "#F8FAEB" },
    { name: "Sand White", hex: "#F7FAED" },
    { name: "Chalky White", hex: "#EFF7E7" },
    { name: "Morrinsville Double", hex: "#F0F7E5" },
    { name: "Cream", hex: "#E2EFDF" },
    { name: "Lunar White", hex: "#D5D8C8" },
    { name: "Hatteras Off-White", hex: "#F7F9EA" },
    { name: "Hatteras Off-White 4208", hex: "#F1F6DF" },
    { name: "Biscuit", hex: "#E6F0CF" },
    { name: "Light Ivory", hex: "#E5EEC1" },
    { name: "Moon Dust", hex: "#CFD9B2" },
    { name: "Desert Tan", hex: "#A8BA9E" },
    { name: "Grand Banks Beige", hex: "#BBB18B" },
    { name: "Grand Banks Beige 4217", hex: "#97A281" },
    { name: "Desert Sand", hex: "#9A9769" },
    { name: "Castle Tan", hex: "#90865F" },
    { name: "Prairie Beige", hex: "#AB7D3C" },
    { name: "Bristol Beige", hex: "#DDBF81" },
    { name: "Pale Gold", hex: "#634927" },
    { name: "Cordovan Gold", hex: "#594D17" },
    { name: "Bronze", hex: "#1E1B18" },
    { name: "Super Jet Black", hex: "#121413" },
    { name: "Shark", hex: "#1E2020" },
    { name: "Anthracite Gray", hex: "#141717" },
    { name: "Dark Gray", hex: "#31444A" },
    { name: "Haze Gray", hex: "#465156" },
    { name: "Medium Gray", hex: "#50646D" },
    { name: "Silver", hex: "#606D6C" },
    { name: "Medium Silver", hex: "#91A4A5" },
    { name: "Bright Aluminum", hex: "#95ABAC" },
    { name: "Snow White Revisited", hex: "#F9FDFF" },
    { name: "Blue Glo White", hex: "#F5FBF6" },
    { name: "Clipper White", hex: "#F4FBF9" },
    { name: "Snow White", hex: "#F6FCFE" },
    { name: "Cloud White", hex: "#F4FCFE" },
    { name: "Signal White", hex: "#F1FBFC" },
    { name: "Blanc Pur", hex: "#F7FAEF" },
    { name: "Oyster White", hex: "#F7F9EA" },
    { name: "Off White", hex: "#F3F9F4" },
    { name: "Stark White", hex: "#F6FAF4" },
    { name: "Insignia White", hex: "#F5FAF4" },
    { name: "Fleet White", hex: "#EFF9F3" },
    { name: "Silver White", hex: "#E4F2E7" },
    { name: "Brightside Off-White", hex: "#F4F9EB" },
    { name: "Vanila White", hex: "#F3F8E3" },
    { name: "Egg Shell White", hex: "#F1F8EC" },
    { name: "Nordic White", hex: "#CFD4C1" },
    { name: "Graystone", hex: "#E5F1DA" },
    { name: "Off-White Revisited", hex: "#E6F5EB" },
    { name: "Matterhorn White", hex: "#E9F5F1" },
    { name: "Vestal White", hex: "#ECF8F4" },
    { name: "Blue Tone White", hex: "#E1F5F5" },
    { name: "Ice Blue", hex: "#D8F4FC" },
    { name: "Aqua Mist", hex: "#D4F2F4" },
    { name: "Kingston Gray", hex: "#A3AFAC" },
    { name: "Light Gray", hex: "#B2B7AC" },
    { name: "Seattle Gray", hex: "#BFCCBD" },
    { name: "Pearl Gray", hex: "#C5CEC5" },
    { name: "Whisper Gray", hex: "#BFCED0" },
    { name: "Chevy Gray", hex: "#DCE9E8" },
  ],
};

export const secondaryInteriorColorCodes = {
  "#B8AB9E": "#a18f7d",
  "#d1d1d1": "#454545",
};

export const variants = {
  "Prophet": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["AL192_FP.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Suzuki Interface", price: 14000 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Mercury Interface (for Simrad)", price: 14000 },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        // { name: "Yamaha Interface (for Simrad)", price: 14000 },
        // {
        //   name: "Hydraulic Cylinder (DF115 - DF140 w/ Hydl Strg)",
        //   price: 14000,
        // },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      //],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes (Tri-Log)", price: 750 },
        { name: "Full Spray Shield for Tri-Log", price: 750 },
        { name: "Spray Shield 3/4 (2-Log)", price: 750 },
        { name: "Spray Shield Full (2-Log)", price: 750 },
        { name: "Atlantis Deck Upgrade", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Chrome Light Housing w/ Dock Side Light", price: 85 },
        {
          name: "EXCHange Chrome for Smoked Chrome Light Housing (For Black Rails)",
          price: 185,
        },
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "Docking Lights", price: 165 },
        { name: "GPS Speedo", price: 165 },
        { name: "Hour Meter", price: 165 },
        { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
        { name: "In Dash Depth Gauge", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lighting (Transom)", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "Courtesy Light on Console", price: 165 },
        { name: "Trim Gauge Honda", price: 165 },
        { name: "Trim Gauge Mercury", price: 165 },
        { name: "Trim Gauge Yamaha", price: 165 },
        { name: "12V Trolling Motor Harness", price: 165 },
        { name: "24V Trolling Motor Harness", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Interior Package - Flint Grey", price: 495 },
        { name: "Interior Package - Taupe", price: 495 },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        { name: "Extend 'L' Seat from 30' to 45'", price: 495 },
        { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
        { name: "Fishing Chair Complete", price: 495 },
        { name: "Fishing Chair - EXCH for IB Capt. Chair", price: 495 },
        { name: "Fishing Chair - EXCH for AT Capt. Chair", price: 495 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
        { name: "Upgrade 192 Console to IB Console", price: 495 },
        { name: "Remove IB Console and Install 192 Console", price: 495 },
        {
          name: "Exchange AT Console for SI Console w/ 12' Simrad",
          price: 495,
        },
      ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        { name: "Cleats - EXCHange Std for Fold Down (2 pr)", price: 375 },
        { name: "Cup Holder, Portable A'Lure", price: 475 },
        { name: "Tilt Steering", price: 375 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Ladder Upgrade to Atlantis", price: 375 },
        {
          name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
          price: 375,
        },
        { name: "Portable Rod Holder Insert", price: 375 },
        { name: "Rod Holder Complete", price: 375 },
        { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
        { name: "Table Complete - Oval - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        {
          name: "46 Gallon Gas Tank Upgrade (Req. Tri-Log Package)",
          price: 375,
        },
        { name: "Livewell - Fiberglass", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
  // "A'Lure 212 Fish": {
  //   initialOptions: {
  //     "Select your Engine (multi-select)": [],
  //     // "Rigging (multi-select)": [],
  //     "Construction options (multi-select)": [],
  //     "Electronics / Lighting (multi-select)": [],
  //     "Appearance Options (multi-select)": [],
  //     "Misc. Options (multi-select)": [],
  //     "Mooring Covers (multi-select)": [],
  //     "Trailer options (multi-select)": [],
  //     // "Financing options (single select)": null,
  //     // "Shipping options (single select)": null,
  //   },
  //   images: ["AL212_FP.png"],
  //   options: {
  //     "Select your Engine (multi-select)": [
  //       // { name: "Suzuki Pre-Rig", price: 13000 },
  //       // { name: "Suzuki Pre-Rig DTS", price: 13800 },
  //       // { name: "Suzuki Interface", price: 14000 },
  //       // { name: "Mercury Pre-Rig", price: 14000 },
  //       // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
  //       // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
  //       // {
  //       //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
  //       //   price: 14000,
  //       // },
  //       // { name: "Mercury Interface (for Simrad)", price: 14000 },
  //       // { name: "Honda Pre-Rig", price: 14000 },
  //       // { name: "Honda Pre-Rig IST", price: 14000 },
  //       // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
  //       // { name: "Yamaha Pre-Rig", price: 14000 },
  //       // { name: "Yamaha Pre-Rig DTS", price: 14000 },
  //       // { name: "Yamaha Interface (for Simrad)", price: 14000 },
  //       // {
  //       //   name: "Hydraulic Cylinder (DF115 - DF140 w/ Hydl Strg)",
  //       //   price: 14000,
  //       // },
  //       { name: "Mercury", price: 13000 },
  //       { name: "Yamaha", price: 13000 },
  //       { name: "Suzuki", price: 13000 },
  //       { name: "Honda", price: 13000 },
  //     ],
  //     // "Rigging (multi-select)": [
  //     //   { name: "Hang Motor Only", price: 6400 },
  //     //   { name: "Full Rig", price: 7200 },
  //     //   { name: "Full Rig DTS", price: 8100 },
  //     //   { name: "Water Ready", price: 9100 },
  //     // ],
  //     "Construction options (multi-select)": [
  //       { name: "25' Transom", price: 600 },
  //       { name: "Tri-Log Package", price: 750 },
  //       { name: "Upgrade Brutus Logs/Tri", price: 750 },
  //       { name: "Full Keel 2-Log", price: 750 },
  //       { name: "Full Keel 3-Log", price: 750 },
  //       {
  //         name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
  //         price: 750,
  //       },
  //       { name: "Lifting Strakes (Tri-Log)", price: 750 },
  //       { name: "Full Spray Shield for Tri-Log", price: 750 },
  //       { name: "Spray Shield 3/4 (2-Log)", price: 750 },
  //       { name: "Spray Shield Full (2-Log)", price: 750 },
  //       { name: "Atlantis Deck Upgrade", price: 750 },
  //     ],
  //     "Electronics / Lighting (multi-select)": [
  //       { name: "Chrome Light Housing w/ Dock Side Lights", price: 85 },
  //       {
  //         name: "EXCHange Chrome for Smoked Chrome Light Housing (For Black Rails)",
  //         price: 185,
  //       },
  //       { name: "Cell Phone Holder w/ Charging Port", price: 165 },
  //       { name: "Docking Lights", price: 165 },
  //       { name: "GPS Speedo", price: 165 },
  //       { name: "Hour Meter", price: 165 },
  //       { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
  //       { name: "In Dash Depth Gauge", price: 165 },
  //       { name: "LED Under Seat Lighting", price: 165 },
  //       { name: "LED Under Water Lighting (Transom)", price: 165 },
  //       { name: "Dual Battery Shut-Off Switch", price: 165 },
  //       { name: "Courtesy Light on Console", price: 165 },
  //       { name: "Trim Gauge Honda", price: 165 },
  //       { name: "Trim Gauge Mercury", price: 165 },
  //       { name: "Trim Gauge Yamaha", price: 165 },
  //       { name: "24V Trolling Motor Harness EXCH", price: 165 },
  //     ],
  //     "Appearance Options (multi-select)": [
  //       { name: "Interior Package - Flint Grey", price: 495 },
  //       { name: "Interior Package - Taupe", price: 495 },
  //       { name: "Upcharge/Upholstery Non-Standard", price: 575 },
  //       { name: "Black Painted Rails and Bimini Frame", price: 575 },
  //       { name: "Dressing Room", price: 575 },
  //       { name: "Extend 'L' Seat from 30' to 45'", price: 495 },
  //       { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
  //       { name: "Fishing Chair Complete", price: 495 },
  //       { name: "Fishing Chair - EXCH for IB Capt. Chair", price: 495 },
  //       { name: "Fishing Chair - EXCH for AT Capt. Chair", price: 495 },
  //       { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
  //       { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
  //       { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
  //       { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
  //       {
  //         name: "Upgrade Console to AT Console (AT Chaise Required in Front of Console)",
  //         price: 495,
  //       },
  //       { name: "Remove IB Console and Install 192 Console", price: 495 },
  //       {
  //         name: "Exchange AT Console for SI Console w/ 12' Simrad",
  //         price: 495,
  //       },
  //     ],
  //     "Misc. Options (multi-select)": [
  //       { name: "Ski Tow Walk Through", price: 90 },
  //       { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
  //       { name: "Cleats - EXCHange Std for Fold Down (2 pr)", price: 375 },
  //       { name: "Cup Holder, Portable A'Lure", price: 475 },
  //       { name: "Tilt Steering", price: 375 },
  //       { name: "Hydraulic Steering/Seastar", price: 375 },
  //       { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
  //       { name: "Ladder Upgrade to Atlantis", price: 375 },
  //       {
  //         name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
  //         price: 375,
  //       },
  //       { name: "Portable Rod Holder Insert", price: 375 },
  //       { name: "Rod Holder Complete", price: 375 },
  //       { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
  //       { name: "Table Complete - Oval - Grey or Tan", price: 375 },
  //       { name: "Extra Table Base", price: 375 },
  //       { name: "Trolling Motor Gate EXCH", price: 375 },
  //       { name: "Sacrificial Anode (For Salt Water)", price: 375 },
  //       { name: "Under Deck Strips", price: 375 },
  //       { name: "U Bolts 16ft. From Bow", price: 375 },
  //       {
  //         name: "46 Gallon Gas Tank Upgrade (Req. Tri-Log Package)",
  //         price: 375,
  //       },
  //       { name: "Livewell - Fiberglass", price: 375 },
  //       { name: "55 Gallon Livewell", price: 375 },
  //     ],
  //     "Mooring Covers (multi-select)": [
  //       { name: "Mooring Cover", price: 90 },
  //       { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
  //     ],
  //     "Trailer options (multi-select)": [
  //       { name: "Trailer - 192", price: 2650 },
  //       { name: "Spare Tire", price: 3150 },
  //       { name: "Spare Tire Carrier", price: 375 },
  //     ],
  //     // "Financing options (single select)": [
  //     //   { name: "C.O.D.", price: 2650 },
  //     //   { name: "Northpoint", price: 3150 },
  //     // ],
  //     // "Shipping options (single select)": [
  //     //   { name: "Dealer Pickup", price: 2650 },
  //     //   { name: "Single/Double Pull", price: 3150 },
  //     //   { name: "Semi Truck", price: 375 },
  //     // ],
  //   },
  // },
  // "A'Lure 212 Fish CC": {
  //   initialOptions: {
  //     "Select your Engine (multi-select)": [],
  //     // "Rigging (multi-select)": [],
  //     "Construction options (multi-select)": [],
  //     "Electronics / Lighting (multi-select)": [],
  //     "Appearance Options (multi-select)": [],
  //     "Misc. Options (multi-select)": [],
  //     "Mooring Covers (multi-select)": [],
  //     "Trailer options (multi-select)": [],
  //     // "Financing options (single select)": null,
  //     // "Shipping options (single select)": null,
  //   },
  //   images: ["AL212CC_FP.png"],
  //   options: {
  //     "Select your Engine (multi-select)": [
  //       // { name: "Suzuki Pre-Rig", price: 13000 },
  //       // { name: "Suzuki Pre-Rig DTS", price: 13800 },
  //       // { name: "Suzuki Interface", price: 14000 },
  //       // { name: "Mercury Pre-Rig", price: 14000 },
  //       // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
  //       // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
  //       // {
  //       //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
  //       //   price: 14000,
  //       // },
  //       // { name: "Mercury Interface (for Simrad)", price: 14000 },
  //       // { name: "Honda Pre-Rig", price: 14000 },
  //       // { name: "Honda Pre-Rig IST", price: 14000 },
  //       // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
  //       // { name: "Yamaha Pre-Rig", price: 14000 },
  //       // { name: "Yamaha Pre-Rig DTS", price: 14000 },
  //       // { name: "Yamaha Interface (for Simrad)", price: 14000 },
  //       // {
  //       //   name: "Hydraulic Cylinder (DF115 - DF140 w/ Hydl Strg)",
  //       //   price: 14000,
  //       // },
  //       { name: "Mercury", price: 13000 },
  //       { name: "Yamaha", price: 13000 },
  //       { name: "Suzuki", price: 13000 },
  //       { name: "Honda", price: 13000 },
  //     ],
  //     // "Rigging (multi-select)": [
  //     //   { name: "Hang Motor Only", price: 6400 },
  //     //   { name: "Full Rig", price: 7200 },
  //     //   { name: "Full Rig DTS", price: 8100 },
  //     //   { name: "Water Ready", price: 9100 },
  //     // ],
  //     "Construction options (multi-select)": [
  //       { name: "25' Transom", price: 600 },
  //       { name: "Tri-Log Package", price: 750 },
  //       { name: "Upgrade Brutus Logs/Tri", price: 750 },
  //       { name: "Full Keel 2-Log", price: 750 },
  //       { name: "Full Keel 3-Log", price: 750 },
  //       {
  //         name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
  //         price: 750,
  //       },
  //       { name: "Lifting Strakes (Tri-Log)", price: 750 },
  //       { name: "Full Spray Shield for Tri-Log", price: 750 },
  //       { name: "Spray Shield 3/4 (2-Log)", price: 750 },
  //       { name: "Spray Shield Full (2-Log)", price: 750 },
  //       { name: "Atlantis Deck Upgrade", price: 750 },
  //     ],
  //     "Electronics / Lighting (multi-select)": [
  //       { name: "Chrome Light Housing w/ Dock Side Lights", price: 85 },
  //       {
  //         name: "Exchange Chrome for Smoked Chrome Light Housing (For Black Rails)",
  //         price: 185,
  //       },
  //       { name: "Cell Phone Holder w/ Charging Port", price: 165 },
  //       { name: "Docking Lights", price: 165 },
  //       { name: "Hour Meter", price: 165 },
  //       { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
  //       { name: "In Dash Depth Gauge", price: 165 },
  //       { name: "LED Under Seat Lighting", price: 165 },
  //       { name: "LED Under Water Lighting (Transom)", price: 165 },
  //       { name: "Dual Battery Shut-Off Switch", price: 165 },
  //       { name: "Courtesy Light on Console", price: 165 },
  //       { name: "Trim Gauge Honda", price: 165 },
  //       { name: "Trim Gauge Mercury", price: 165 },
  //       { name: "Trim Gauge Yamaha", price: 165 },
  //       { name: "24V Trolling Motor Harness EXCH", price: 165 },
  //     ],
  //     "Appearance Options (multi-select)": [
  //       { name: "Interior Package - Flint Grey", price: 495 },
  //       { name: "Interior Package - Taupe", price: 495 },
  //       {
  //         name: "Interior Package - Cognac (Cool Technology) (Must Upgrade to Atlantis Capt. Chair) ",
  //         price: 495,
  //       },
  //       {
  //         name: "Interior Package - Anthracite (Cool Technology) (Must Upgrade to Atlantis Capt. Chair) ",
  //         price: 495,
  //       },
  //       { name: "Upcharge/Upholstery Non-Standard", price: 575 },
  //       { name: "Black Painted Rails and Bimini Frame", price: 575 },
  //       { name: "Extend 'L' Seat from 30' to 45'", price: 495 },
  //       { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
  //       { name: "Fishing Chair Complete", price: 495 },
  //       { name: "Fishing Chair - EXCH for IB Capt. Chair", price: 495 },
  //       { name: "Fishing Chair - EXCH for AT Capt. Chair", price: 495 },
  //       { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
  //       { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
  //       { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
  //       { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
  //       { name: "Remove IB Console and Install 192 Console", price: 495 },
  //       {
  //         name: "Exchange AT Console for SI Console w/ 12' Simrad",
  //         price: 495,
  //       },
  //     ],
  //     "Misc. Options (multi-select)": [
  //       { name: "Ski Tow Walk Through", price: 90 },
  //       { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
  //       { name: "Cleats - Exchange Std for Fold Down (2 pr)", price: 375 },
  //       { name: "Cup Holder, Portable A'Lure", price: 475 },
  //       { name: "Tilt Steering", price: 375 },
  //       { name: "Hydraulic Steering/Seastar", price: 375 },
  //       { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
  //       { name: "Ladder Upgrade to Atlantis", price: 375 },
  //       {
  //         name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
  //         price: 375,
  //       },
  //       { name: "Portable Rod Holder Insert", price: 375 },
  //       { name: "Rod Holder Complete", price: 375 },
  //       { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
  //       { name: "Table Complete - Oval - Grey or Tan", price: 375 },
  //       { name: "Extra Table Base", price: 375 },
  //       { name: "Starboard Gate", price: 375 },
  //       { name: "Trolling Motor Gate EXCH", price: 375 },
  //       { name: "Sacrificial Anode (For Salt Water)", price: 375 },
  //       { name: "Under Deck Strips", price: 375 },
  //       { name: "U Bolts 16ft. From Bow", price: 375 },
  //       {
  //         name: "46 Gallon Gas Tank Upgrade (Req. Tri-Log Package)",
  //         price: 375,
  //       },
  //       { name: "Livewell - Fiberglass", price: 375 },
  //     ],
  //     "Mooring Covers (multi-select)": [
  //       { name: "Mooring Cover", price: 90 },
  //       { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
  //     ],
  //     "Trailer options (multi-select)": [
  //       { name: "Trailer - 192", price: 2650 },
  //       { name: "Spare Tire", price: 3150 },
  //       { name: "Spare Tire Carrier", price: 375 },
  //     ],
  //     // "Financing options (single select)": [
  //     //   { name: "C.O.D.", price: 2650 },
  //     //   { name: "Northpoint", price: 3150 },
  //     // ],
  //     // "Shipping options (single select)": [
  //     //   { name: "Dealer Pickup", price: 2650 },
  //     //   { name: "Single/Double Pull", price: 3150 },
  //     //   { name: "Semi Truck", price: 375 },
  //     // ],
  //   },
  // },
  // "A'Lure 232 Fish CC": {
  //   initialOptions: {
  //     "Select your Engine (multi-select)": [],
  //     // "Rigging (multi-select)": [],
  //     "Construction options (multi-select)": [],
  //     "Electronics / Lighting (multi-select)": [],
  //     "Appearance Options (multi-select)": [],
  //     "Misc. Options (multi-select)": [],
  //     "Mooring Covers (multi-select)": [],
  //     "Trailer options (multi-select)": [],
  //     // "Financing options (single select)": null,
  //     // "Shipping options (single select)": null,
  //   },
  //   images: ["AL232_FP.png"],
  //   options: {
  //     "Select your Engine (multi-select)": [
  //       // { name: "Suzuki Pre-Rig", price: 13000 },
  //       // { name: "Suzuki Pre-Rig DTS", price: 13800 },
  //       // { name: "Suzuki Interface", price: 14000 },
  //       // { name: "Mercury Pre-Rig", price: 14000 },
  //       // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
  //       // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
  //       // {
  //       //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
  //       //   price: 14000,
  //       // },
  //       // { name: "Mercury Interface (for Simrad)", price: 14000 },
  //       // { name: "Honda Pre-Rig", price: 14000 },
  //       // { name: "Honda Pre-Rig IST", price: 14000 },
  //       // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
  //       // { name: "Yamaha Pre-Rig", price: 14000 },
  //       // { name: "Yamaha Pre-Rig DTS", price: 14000 },
  //       // { name: "Yamaha Interface (for Simrad)", price: 14000 },
  //       // {
  //       //   name: "Hydraulic Cylinder (DF115 - DF140 w/ Hydl Strg)",
  //       //   price: 14000,
  //       // },
  //       { name: "Mercury", price: 13000 },
  //       { name: "Yamaha", price: 13000 },
  //       { name: "Suzuki", price: 13000 },
  //       { name: "Honda", price: 13000 },
  //     ],
  //     // "Rigging (multi-select)": [
  //     //   { name: "Hang Motor Only", price: 6400 },
  //     //   { name: "Full Rig", price: 7200 },
  //     //   { name: "Full Rig DTS", price: 8100 },
  //     //   { name: "Water Ready", price: 9100 },
  //     // ],
  //     "Construction options (multi-select)": [
  //       { name: "25' Transom", price: 600 },
  //       { name: "Tri-Log Package", price: 750 },
  //       { name: "Upgrade Brutus Logs/Tri", price: 750 },
  //       { name: "Full Keel 2-Log", price: 750 },
  //       { name: "Full Keel 3-Log", price: 750 },
  //       {
  //         name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
  //         price: 750,
  //       },
  //       { name: "Lifting Strakes (Tri-Log)", price: 750 },
  //       { name: "Full Spray Shield for Tri-Log", price: 750 },
  //       { name: "Spray Shield 3/4 (2-Log)", price: 750 },
  //       { name: "Spray Shield Full (2-Log)", price: 750 },
  //       { name: "Atlantis Deck Upgrade", price: 750 },
  //     ],
  //     "Electronics / Lighting (multi-select)": [
  //       { name: "Chrome Light Housing w/ Dock Side Lights", price: 85 },
  //       {
  //         name: "Exchange Chrome for Smoked Chrome Light Housing (For Black Rails)",
  //         price: 185,
  //       },
  //       { name: "Cell Phone Holder w/ Charging Port", price: 165 },
  //       { name: "Docking Lights", price: 165 },
  //       { name: "Hour Meter", price: 165 },
  //       { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
  //       { name: "In Dash Depth Gauge", price: 165 },
  //       { name: "LED Under Seat Lighting", price: 165 },
  //       { name: "LED Under Water Lighting (Transom)", price: 165 },
  //       { name: "Dual Battery Shut-Off Switch", price: 165 },
  //       { name: "Courtesy Light on Console", price: 165 },
  //       { name: "Trim Gauge Honda", price: 165 },
  //       { name: "Trim Gauge Mercury", price: 165 },
  //       { name: "Trim Gauge Yamaha", price: 165 },
  //       { name: "24V Trolling Motor Harness EXCH", price: 165 },
  //     ],
  //     "Appearance Options (multi-select)": [
  //       { name: "Interior Package - Flint Grey", price: 495 },
  //       { name: "Interior Package - Taupe", price: 495 },
  //       {
  //         name: "Interior Package - Cognac (Cool Technology) (Must Upgrade to Atlantis Capt. Chair) ",
  //         price: 495,
  //       },
  //       {
  //         name: "Interior Package - Anthracite (Cool Technology) (Must Upgrade to Atlantis Capt. Chair) ",
  //         price: 495,
  //       },
  //       { name: "Upcharge/Upholstery Non-Standard", price: 575 },
  //       { name: "Black Painted Rails and Bimini Frame", price: 575 },
  //       { name: "Extend 'L' Seat from 30' to 45'", price: 495 },
  //       { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
  //       { name: "Fishing Chair Complete", price: 495 },
  //       { name: "Fishing Chair - EXCH for IB Capt. Chair", price: 495 },
  //       { name: "Fishing Chair - EXCH for AT Capt. Chair", price: 495 },
  //       { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
  //       { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
  //       { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
  //       { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
  //       { name: "Remove IB Console and Install 192 Console", price: 495 },
  //       {
  //         name: "Exchange AT Console for SI Console w/ 12' Simrad",
  //         price: 495,
  //       },
  //     ],
  //     "Misc. Options (multi-select)": [
  //       { name: "Ski Tow Walk Through", price: 90 },
  //       { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
  //       { name: "Cleats - Exchange Std for Fold Down (2 pr)", price: 375 },
  //       { name: "Cup Holder, Portable A'Lure", price: 475 },
  //       { name: "Tilt Steering", price: 375 },
  //       { name: "Hydraulic Steering/Seastar", price: 375 },
  //       { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
  //       { name: "Ladder Upgrade to Atlantis", price: 375 },
  //       {
  //         name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
  //         price: 375,
  //       },
  //       { name: "Portable Rod Holder Insert", price: 375 },
  //       { name: "Rod Holder Complete", price: 375 },
  //       { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
  //       { name: "Table Complete - Oval - Grey or Tan", price: 375 },
  //       { name: "Extra Table Base", price: 375 },
  //       { name: "Starboard Gate", price: 375 },
  //       { name: "Trolling Motor Gate EXCH", price: 375 },
  //       { name: "Sacrificial Anode (For Salt Water)", price: 375 },
  //       { name: "Under Deck Strips", price: 375 },
  //       { name: "U Bolts 16ft. From Bow", price: 375 },
  //       {
  //         name: "46 Gallon Gas Tank Upgrade (Req. Tri-Log Package)",
  //         price: 375,
  //       },
  //       { name: "Livewell - Fiberglass", price: 375 },
  //     ],
  //     "Mooring Covers (multi-select)": [
  //       { name: "Mooring Cover", price: 90 },
  //       { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
  //     ],
  //     "Trailer options (multi-select)": [
  //       { name: "Trailer - 192", price: 2650 },
  //       { name: "Spare Tire", price: 3150 },
  //       { name: "Spare Tire Carrier", price: 375 },
  //     ],
  //     // "Financing options (single select)": [
  //     //   { name: "C.O.D.", price: 2650 },
  //     //   { name: "Northpoint", price: 3150 },
  //     // ],
  //     // "Shipping options (single select)": [
  //     //   { name: "Dealer Pickup", price: 2650 },
  //     //   { name: "Single/Double Pull", price: 3150 },
  //     //   { name: "Semi Truck", price: 375 },
  //     // ],
  //   },
  // },
  // "A'Lure 224": {
  //   initialOptions: {
  //     "Select your Engine (multi-select)": [],
  //     // "Rigging (multi-select)": [],
  //     "Construction options (multi-select)": [],
  //     "Electronics / Lighting (multi-select)": [],
  //     "Appearance Options (multi-select)": [],
  //     "Misc. Options (multi-select)": [],
  //     "Mooring Covers (multi-select)": [],
  //     "Trailer options (multi-select)": [],
  //     // "Financing options (single select)": null,
  //     // "Shipping options (single select)": null,
  //   },
  //   images: ["AL224_FP.png"],
  //   options: {
  //     "Select your Engine (multi-select)": [
  //       // { name: "Suzuki Pre-Rig A'Lure 224", price: 13000 },
  //       // { name: "Suzuki Pre-Rig DTS", price: 13800 },
  //       // { name: "Suzuki Interface", price: 14000 },
  //       // { name: "Mercury Pre-Rig", price: 14000 },
  //       // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
  //       // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
  //       // {
  //       //   name: "Mercury Pre-Rig Verado DTS Pwr Strg A'Lure 224",
  //       //   price: 14000,
  //       // },
  //       // {
  //       //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
  //       //   price: 14000,
  //       // },
  //       // { name: "Mercury Interface (for Simrad)", price: 14000 },
  //       // { name: "Honda Pre-Rig", price: 14000 },
  //       // { name: "Honda Pre-Rig IST", price: 14000 },
  //       // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
  //       // { name: "Yamaha Pre-Rig", price: 14000 },
  //       // { name: "Yamaha Pre-Rig DTS", price: 14000 },
  //       // { name: "Yamaha Interface (for Simrad)", price: 14000 },
  //       // {
  //       //   name: "Hydraulic Cylinder (DF115 - DF140 w/ Hydl Strg)",
  //       //   price: 14000,
  //       // },
  //       { name: "Mercury", price: 13000 },
  //       { name: "Yamaha", price: 13000 },
  //       { name: "Suzuki", price: 13000 },
  //       { name: "Honda", price: 13000 },
  //     ],
  //     // "Rigging (multi-select)": [
  //     //   { name: "Hang Motor Only", price: 6400 },
  //     //   { name: "Full Rig", price: 7200 },
  //     //   { name: "Full Rig DTS", price: 8100 },
  //     //   { name: "Water Ready", price: 9100 },
  //     // ],
  //     "Construction options (multi-select)": [
  //       { name: "25' Transom", price: 600 },
  //       { name: "Tri-Log Package", price: 750 },
  //       { name: "Tri-Log Package w/ Ski Storage", price: 750 },
  //       { name: "Upgrade Brutus Logs/Tri", price: 750 },
  //       { name: "Upgrade Brutus Logs/Tri w/ Ski Storage", price: 750 },
  //       { name: "Full Keel 2-Log", price: 750 },
  //       { name: "Full Keel 3-Log", price: 750 },
  //       {
  //         name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
  //         price: 750,
  //       },
  //       { name: "Lifting Strakes (Tri-Log)", price: 750 },
  //       { name: "Full Spray Shield for Tri-Log", price: 750 },
  //       { name: "Spray Shield 3/4 (2-Log)", price: 750 },
  //       { name: "Spray Shield Full (2-Log)", price: 750 },
  //       { name: "Atlantis Deck Upgrade", price: 750 },
  //     ],
  //     "Electronics / Lighting (multi-select)": [
  //       { name: "Chrome Light Housing w/ Dock Side Lights", price: 85 },
  //       {
  //         name: "Exchange Chrome for Smoked Chrome Light Housing (For Black Rails)",
  //         price: 185,
  //       },
  //       { name: "Cell Phone Holder w/ Charging Port", price: 165 },
  //       { name: "Hour Meter", price: 165 },
  //       { name: "Fish Finder - GPS Lowrance Hook 2-4", price: 165 },
  //       { name: "In Dash Depth Gauge", price: 165 },
  //       { name: "LED Under Seat Lighting", price: 165 },
  //       { name: "LED Under Water Lighting (Transom)", price: 165 },
  //       { name: "Dual Battery Shut-Off Switch", price: 165 },
  //       { name: "Courtesy Light on Console", price: 165 },
  //       { name: "Trim Gauge Honda", price: 165 },
  //       { name: "Trim Gauge Mercury", price: 165 },
  //       { name: "Trim Gauge Yamaha", price: 165 },
  //       { name: "24V Trolling Motor Harness EXCH", price: 165 },
  //     ],
  //     "Appearance Options (multi-select)": [
  //       { name: "Top Panel Graphic", price: 495 },
  //       { name: "Interior Package - Flint Grey", price: 495 },
  //       { name: "Interior Package - Taupe", price: 495 },
  //       { name: "Interior Package - Cognac (Cool Technology)", price: 495 },
  //       { name: "Interior Package - Anthracite (Cool Technology)", price: 495 },
  //       { name: "Upcharge/Upholstery Non-Standard", price: 575 },
  //       { name: "Black Painted Rails and Bimini Frame", price: 575 },
  //       { name: "Dressing Room (224) Remove Chaise Add DR", price: 575 },
  //       { name: "Extend 'L' Seat from 30' to 45'", price: 495 },
  //       { name: "Exchange 30' Couch for 33' Lean Back Couch", price: 495 },
  //       { name: "Fishing Chair Complete", price: 495 },
  //       { name: "Fishing Chair - EXCH for IB Capt. Chair", price: 495 },
  //       { name: "Fishing Chair - EXCH for AT Capt. Chair", price: 495 },
  //       { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
  //       { name: "Flooring Upgrade - Grey Plank Flint", price: 495 },
  //       { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
  //       { name: "Flooring Upgrade - Taupe Plank Shadow", price: 495 },
  //       { name: "Remove IB Console and Install 192 Console", price: 495 },
  //       {
  //         name: "Exchange AT Console for SI Console w/ 12' Simrad",
  //         price: 495,
  //       },
  //     ],
  //     "Top Panel Graphic Color (multi-select)": [
  //       { name: "Matte Black", price: 90 },
  //       { name: "Grey", price: 420 },
  //       { name: "Deep Blue", price: 90 },
  //       { name: "Merlot", price: 420 },
  //       { name: "Deep Red", price: 90 },
  //       { name: "White", price: 420 },
  //       { name: "Steel Blue", price: 90 },
  //     ],
  //     "Misc. Options (multi-select)": [
  //       { name: "Ski Tow Walk Through", price: 90 },
  //       { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
  //       { name: "Cleats - Exchange Std for Fold Down (2 pr)", price: 375 },
  //       { name: "Cleats - Exchange Std for Pull Up (2 pr)", price: 375 },
  //       { name: "Cup Holder, Portable A'Lure", price: 475 },
  //       { name: "Hydraulic Steering/Seastar", price: 375 },
  //       { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
  //       { name: "Ladder Upgrade to Signature", price: 375 },
  //       {
  //         name: "Lockable Rod Storage (Adj. Ped. Req. if Helm Chair Upgrade)",
  //         price: 375,
  //       },
  //       { name: "Portable Rod Holder Insert", price: 375 },
  //       { name: "Rod Holder Complete", price: 375 },
  //       { name: "Table Complete - Kidney - Grey or Tan", price: 375 },
  //       { name: "Table Complete - Oval - Grey or Tan", price: 375 },
  //       { name: "Extra Table Base", price: 375 },
  //       { name: "Trolling Motor Gate EXCH", price: 375 },
  //       { name: "Sacrificial Anode (For Salt Water)", price: 375 },
  //       { name: "Under Deck Strips", price: 375 },
  //       { name: "U Bolts 16ft. From Bow", price: 375 },
  //       {
  //         name: "46 Gallon Gas Tank Upgrade (Req. Tri-Log Package)",
  //         price: 375,
  //       },
  //       { name: "Livewell - Fiberglass", price: 375 },
  //     ],
  //     "Mooring Covers (multi-select)": [
  //       { name: "Mooring Cover", price: 90 },
  //       { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
  //     ],
  //     "Trailer options (multi-select)": [
  //       { name: "Trailer - 192", price: 2650 },
  //       { name: "Spare Tire", price: 3150 },
  //       { name: "Spare Tire Carrier", price: 375 },
  //     ],
  //     // "Financing options (single select)": [
  //     //   { name: "C.O.D.", price: 2650 },
  //     //   { name: "Northpoint", price: 3150 },
  //     // ],
  //     // "Shipping options (single select)": [
  //     //   { name: "Dealer Pickup", price: 2650 },
  //     //   { name: "Single/Double Pull", price: 3150 },
  //     //   { name: "Semi Truck", price: 375 },
  //     // ],
  //   },
  // },
};
