export const modelParts = [
  "Primary Fence",
  "Secondary Fence",
  "Exterior Rail",
  "Interior Options",
];
export const initialColors = {
  "Primary Fence": "#E3E6D5",
  "Secondary Fence": "#424142",
  "Exterior Rail": "#000000",
  "Interior Options": "#B8AB9E",
};

export const colorOptions = {
  "Primary Fence": [
    {
      name: "Pearl",
      hex: "#E3E6D5",
    },
    { name: "Meriot", hex: "#821B21" },
    {
      name: "Steel Blue",
      hex: "#3B4750",
    },
    {
      name: "Deep Blue",
      hex: "#0D3A66",
    },
    {
      name: "Charcoal",
      hex: "#424142",
    },
    {
      name: "Midnight Black",
      hex: "#000000",
    },
  ],
  "Secondary Fence": [
    {
      name: "Pearl",
      hex: "#E3E6D5",
    },
    { name: "Meriot", hex: "#821B21" },
    {
      name: "Steel Blue",
      hex: "#3B4750",
    },
    {
      name: "Deep Blue",
      hex: "#0D3A66",
    },
    {
      name: "Charcoal",
      hex: "#424142",
    },
    {
      name: "Midnight Black",
      hex: "#000000",
    },
  ],
  "Exterior Rail": [
    {
      name: "Metal",
      hex: "#D5E2E6",
    },
    {
      name: "Black",
      hex: "#000000",
    },
  ],
  "Interior Options": [
    {
      name: "Taupe Series",
      hex: "#B8AB9E",
    },
    {
      name: "Grey Series",
      hex: "#878787",
    },
    {
      name: "Cognac Series",
      hex: "#9C6B3E",
    },
    {
      name: "Anthracite Series",
      hex: "#52555B",
    },
  ],
};

export const secondaryInteriorColorCodes = {
  "#B8AB9E": "#4d3f32",
  "#878787": "#424242",
  "#9C6B3E": "#F1BC8B",
  "#52555B": "#303030",
};

export const variants = {
  "Signature 2200 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["signature_2200.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Mercury Pre-Rig Verado DTS PS", price: 14000 },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Tri-Log Package w/ Ski Storage", price: 750 },
        { name: "Upgrade Brutus Logs/Trilog", price: 750 },
        { name: "Upgrade Brutus Logs/Trilog w/ Ski Storage", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        {
          name: "HHP Tag Brutus(Incl. Lifting Strakes, Hydl Steering) Requires Brutus Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes", price: 750 },
        { name: "Spray Shield - Full for Tri-Log", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lights (Transom)", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Cognac (Cool Technology)", price: 495 },
        { name: "Interior Package - Anthracite (Cool Technology)", price: 495 },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        {
          name: "Black Painted Rails & Bimini Frame (Incl. Smoked Light Housing)",
          price: 495,
        },
        { name: "Fish Rear Seating", price: 575 },
        { name: "Rear Lounge", price: 575 },
        { name: "Split Rear Lounge", price: 575 },
        { name: "Sport Rear", price: 750 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Swing Back Rear Lounge", price: 575 },
        { name: "Chaise Changing Room (Port Front)", price: 575 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal for Helm Exchange", price: 495 },
        //{ name: "Sport Cruise Seating (Capt. Chair Up Front)", price: 750 },
        { name: "Raised Helm", price: 750 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Ski Tow HHP (350HP+)", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        { name: "Wake Board Tower - Split Rear or Sport Rear", price: 90 },
        {
          name: "Power Wake Board Tower - Split Rear or Sport Rear",
          price: 90,
        },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Lilli Pad Diving Board (Anodized)", price: 375 },
        { name: "Lilli Pad Diving Board (Black)", price: 375 },
        { name: "Table Complete - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Mooring Cover (WB Tower Option)", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
        { name: "Twin Bimini (For Tower Option)", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
        { name: "Heavy Duty Trailer Frame", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
  "Signature 2300 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["signature_2300.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Mercury Pre-Rig Verado DTS PS", price: 14000 },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Tri-Log Package w/ Ski Storage", price: 750 },
        { name: "Upgrade Brutus Logs/Trilog", price: 750 },
        { name: "Upgrade Brutus Logs/Trilog w/ Ski Storage", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        {
          name: "HHP Tag Brutus(Incl. Lifting Strakes, Hydl Steering) Requires Brutus Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes", price: 750 },
        { name: "Spray Shield - Full for Tri-Log", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lights (Transom)", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Cognac (Cool Technology)", price: 495 },
        { name: "Interior Package - Anthracite (Cool Technology)", price: 495 },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        {
          name: "Black Painted Rails & Bimini Frame (Incl. Smoked Light Housing)",
          price: 495,
        },
        { name: "Fish Rear Seating", price: 575 },
        { name: "Rear Lounge", price: 575 },
        { name: "Split Rear Lounge", price: 575 },
        { name: "Sport Rear", price: 750 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Swing Back Rear Lounge", price: 575 },
        { name: "Chaise Changing Room (Port Front)", price: 575 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal for Helm Exchange", price: 495 },
        { name: "Sport Cruise Seating (Capt. Chair Up Front)", price: 750 },
        { name: "Raised Helm", price: 750 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Ski Tow HHP (350HP+)", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        { name: "Wake Board Tower - Split Rear or Sport Rear", price: 90 },
        {
          name: "Power Wake Board Tower - Split Rear or Sport Rear",
          price: 90,
        },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Lilli Pad Diving Board (Anodized)", price: 375 },
        { name: "Lilli Pad Diving Board (Black)", price: 375 },
        { name: "Table Complete - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Mooring Cover (WB Tower Option)", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
        { name: "Twin Bimini (For Tower Option)", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
        { name: "Heavy Duty Trailer Frame", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
  "Signature 2500 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["signature_2500.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Mercury Pre-Rig Verado DTS PS", price: 14000 },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Tri-Log Package w/ Ski Storage", price: 750 },
        { name: "Upgrade Brutus Logs/Trilog", price: 750 },
        { name: "Upgrade Brutus Logs/Trilog w/ Ski Storage", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        {
          name: "HHP Tag Brutus(Incl. Lifting Strakes, Hydl Steering) Requires Brutus Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes", price: 750 },
        { name: "Spray Shield - Full for Tri-Log", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lights (Transom)", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Cognac (Cool Technology)", price: 495 },
        { name: "Interior Package - Anthracite (Cool Technology)", price: 495 },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        {
          name: "Black Painted Rails & Bimini Frame (Incl. Smoked Light Housing)",
          price: 495,
        },
        { name: "Fish Rear Seating", price: 575 },
        { name: "Rear Lounge", price: 575 },
        { name: "Split Rear Lounge", price: 575 },
        { name: "Sport Rear", price: 750 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Swing Back Rear Lounge", price: 575 },
        { name: "Chaise Changing Room (Port Front)", price: 575 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal for Helm Exchange", price: 495 },
        { name: "Sport Cruise Seating (Capt. Chair Up Front)", price: 750 },
        { name: "Raised Helm", price: 750 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Ski Tow HHP (350HP+)", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        { name: "Wake Board Tower - Split Rear or Sport Rear", price: 90 },
        {
          name: "Power Wake Board Tower - Split Rear or Sport Rear",
          price: 90,
        },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Lilli Pad Diving Board (Anodized)", price: 375 },
        { name: "Lilli Pad Diving Board (Black)", price: 375 },
        { name: "Table Complete - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Mooring Cover (WB Tower Option)", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
        { name: "Twin Bimini (For Tower Option)", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
        { name: "Heavy Duty Trailer Frame", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
  "Signature 2700 Cruise": {
    initialOptions: {
      "Select your Engine (multi-select)": [],
      // "Rigging (multi-select)": [],
      "Construction options (multi-select)": [],
      "Electronics / Lighting (multi-select)": [],
      "Appearance Options (multi-select)": [],
      "Misc. Options (multi-select)": [],
      "Mooring Covers (multi-select)": [],
      "Trailer options (multi-select)": [],
      // "Financing options (single select)": null,
      // "Shipping options (single select)": null,
    },
    images: ["signature_2700.png"],
    options: {
      "Select your Engine (multi-select)": [
        // { name: "Suzuki Pre-Rig", price: 13000 },
        // { name: "Suzuki Pre-Rig DTS", price: 13800 },
        // { name: "Mercury Pre-Rig", price: 14000 },
        // { name: "Mercury Pre-Rig 175HP & Above - Mech", price: 14000 },
        // { name: "Mercury Pre-Rig 175-225 w/o Power Steering V6", price: 14000 },
        // {
        //   name: "Mercury Pre-Rig DTS Power Steering (not Verado)",
        //   price: 14000,
        // },
        // { name: "Mercury Pre-Rig Verado DTS PS", price: 14000 },
        // { name: "Honda Pre-Rig", price: 14000 },
        // { name: "Honda Pre-Rig IST", price: 14000 },
        // { name: "Honda V6 (Not IST) 200 & Up", price: 14000 },
        // { name: "Yamaha Pre-Rig", price: 14000 },
        // { name: "Yamaha Pre-Rig DTS", price: 14000 },
        { name: "Mercury", price: 13000 },
        { name: "Yamaha", price: 13000 },
        { name: "Suzuki", price: 13000 },
        { name: "Honda", price: 13000 },
      ],
      // "Rigging (multi-select)": [
      //   { name: "Hang Motor Only", price: 6400 },
      //   { name: "Full Rig", price: 7200 },
      //   { name: "Full Rig DTS", price: 8100 },
      //   { name: "Water Ready", price: 9100 },
      // ],
      "Construction options (multi-select)": [
        { name: "25' Transom", price: 600 },
        { name: "Tri-Log Package", price: 750 },
        { name: "Tri-Log Package w/ Ski Storage", price: 750 },
        { name: "Upgrade Brutus Logs/Trilog", price: 750 },
        { name: "Upgrade Brutus Logs/Trilog w/ Ski Storage", price: 750 },
        { name: "Full Keel 2-Log", price: 750 },
        { name: "Full Keel 3-Log", price: 750 },
        {
          name: "HHP Tag (Incl. Lifting Strakes, Hydl Steering) Requires Tri-Log Package",
          price: 750,
        },
        {
          name: "HHP Tag Brutus(Incl. Lifting Strakes, Hydl Steering) Requires Brutus Tri-Log Package",
          price: 750,
        },
        { name: "Lifting Strakes", price: 750 },
        { name: "Spray Shield - Full for Tri-Log", price: 750 },
      ],
      "Electronics / Lighting (multi-select)": [
        { name: "Cell Phone Holder w/ Charging Port", price: 165 },
        { name: "LED Under Seat Lighting", price: 165 },
        { name: "LED Under Water Lights (Transom)", price: 165 },
        { name: "RGB Speaker Lighting", price: 165 },
        { name: "Dual Battery Shut-Off Switch", price: 165 },
        { name: "24V Trolling Motor Harness (SC)", price: 165 },
      ],
      "Appearance Options (multi-select)": [
        { name: "Top Panel Graphic", price: 495 },
        { name: "Interior Package - Cognac (Cool Technology)", price: 495 },
        { name: "Interior Package - Anthracite (Cool Technology)", price: 495 },
        { name: "Upcharge/Upholstery Non-Standard", price: 575 },
        {
          name: "Black Painted Rails & Bimini Frame (Incl. Smoked Light Housing)",
          price: 495,
        },
        { name: "Fish Rear Seating", price: 575 },
        { name: "Rear Lounge", price: 575 },
        { name: "Split Rear Lounge", price: 575 },
        { name: "Sport Rear", price: 750 },
        {
          name: "Sport Rear Chair Exch Co-Capt. Chair for 30' Couch",
          price: 575,
        },
        { name: "Swing Back Rear Lounge", price: 575 },
        { name: "Chaise Changing Room (Port Front)", price: 575 },
        { name: "Flooring Upgrade - Grey Teak II Slate", price: 495 },
        { name: "Flooring Upgrade - Taupe Teak Nutmeg", price: 495 },
        { name: "Removable Gate Couch", price: 495 },
        { name: "Adjustable Height Pedestal for Helm Exchange", price: 495 },
        { name: "Sport Cruise Seating (Capt. Chair Up Front)", price: 750 },
        { name: "Raised Helm", price: 750 },
      ],
      // "Top Panel Graphic Color (multi-select)": [
      //   { name: "Matte Black", price: 90 },
      //   { name: "Grey", price: 420 },
      //   { name: "Deep Blue", price: 90 },
      //   { name: "Merlot", price: 420 },
      //   { name: "Deep Red", price: 90 },
      //   { name: "White", price: 420 },
      //   { name: "Steel Blue", price: 90 },
      // ],
      "Misc. Options (multi-select)": [
        { name: "Ski Tow Walk Through", price: 90 },
        { name: "Ski Tow HHP (350HP+)", price: 90 },
        { name: "Tetra Pad (Tube Storage Over Ski Tow)", price: 90 },
        { name: "Wake Board Tower - Split Rear or Sport Rear", price: 90 },
        {
          name: "Power Wake Board Tower - Split Rear or Sport Rear",
          price: 90,
        },
        { name: "Cup Holder, Portable EA", price: 475 },
        { name: "Hydraulic Steering/Seastar", price: 375 },
        { name: "Power Assist-Seastar Incl. Hydraulic Steering", price: 375 },
        { name: "Lilli Pad Diving Board (Anodized)", price: 375 },
        { name: "Lilli Pad Diving Board (Black)", price: 375 },
        { name: "Table Complete - Grey or Tan", price: 375 },
        { name: "Extra Table Base", price: 375 },
        { name: "Trolling Motor Gate EXCH", price: 375 },
        { name: "Sacrificial Anode (For Salt Water)", price: 375 },
        { name: "Under Deck Strips", price: 375 },
        { name: "U Bolts 16ft. From Bow", price: 375 },
        { name: "Aeration for Live Well Front Seat", price: 375 },
        { name: "Phender Pro - PR", price: 375 },
      ],
      "Mooring Covers (multi-select)": [
        { name: "Mooring Cover", price: 90 },
        { name: "Mooring Cover (WB Tower Option)", price: 90 },
        { name: "Upcharge/Mooring Cover Non-Standard", price: 420 },
        { name: "Twin Bimini", price: 90 },
        { name: "Twin Bimini (For Tower Option)", price: 90 },
      ],
      "Trailer options (multi-select)": [
        { name: "Trailer - 192", price: 2650 },
        { name: "Spare Tire", price: 3150 },
        { name: "Spare Tire Carrier", price: 375 },
        { name: "Heavy Duty Trailer Frame", price: 375 },
      ],
      // "Financing options (single select)": [
      //   { name: "C.O.D.", price: 2650 },
      //   { name: "Northpoint", price: 3150 },
      // ],
      // "Shipping options (single select)": [
      //   { name: "Dealer Pickup", price: 2650 },
      //   { name: "Single/Double Pull", price: 3150 },
      //   { name: "Semi Truck", price: 375 },
      // ],
    },
  },
};
